[quote.epigraph, , Isaiah 42:16]
____
Conduciré a los ciegos por un camino que no conocen.
____

== Introducción

Las siguientes páginas contienen la parte esencial
de una carta de la autora a un pariente suyo.
Algunos de sus familiares y varios Amigos que las han leído,
consideran que en ellas se encierra una gran enseñanza para
el viajero Cristiano que ha puesto "`su mano en el arado.`"
Esta obra alienta a inclinarse ante las primeras impresiones del poder del Altísimo,
a estar atentos a la voz del Pastor,
y a permitir que todo en uno se humille en sumisión a Sus mandatos.
Muestra lo importante que es para aquellos (como para la escritora
de esta narración) que han adquirido una herencia en la justicia,
tener cuidado de no soltar su ancla, sino obedecer el mandato del hombre sabio:
"`compra la verdad, y no la vendas.`"
Son un llamado a los que han nacido como miembros en nuestra Sociedad religiosa,
para que valoren su privilegio;
viendo que la situación que tenemos ante nosotros es una muestra, entre muchas otras,
de las dificultades y pruebas por las que tienen que pasar los que son llamados
a salir de este mundo para ser obreros fieles en la viña celestial.

Al ser un ejemplo tan lleno de vida,
es de lamentar que no se encuentren más documentos
del progreso religioso de nuestra querida amiga,
que vivió y murió siendo respetada y amada.^
footnote:[Este relato fue originalmente editado por Frederick Smith;
se publicaron dos ediciones en el año 1797.]
Margaret Lucas murió en Leek, en Staffordshire, el 24 del Sexto Mes de 1769.
