== La Vida de Margaret Lucas

Nací en el año 1701, en Fleet-street, Londres; mi padre, cuyo nombre era James Brindley,
tenía una tienda de porcelana en la esquina de Fetter-lane.
Yo era la menor de 14 hermanos.
Mi madre murió cuando yo tenía un año y medio; después mi padre se mudó a Vauxhall,
donde construyó una alfarería para fabricar cerámica,
y se casó por segunda vez con una mujer, que al fallecer antes que él,
le dejó a su cargo dos hijos.
Mi padre murió cuando yo tenía unos siete años, dejando a seis huérfanos,
dos de ellos menores que yo, sin ningún otro pariente conocido, excepto una tía,
hermana de mi padre,
y que estaba casada con la persona que a continuación se mencionará
como mi tío. Al morir mi padre sin redactar un testamento,
dejó las cosas en desorden; y entonces, Elías Turner,
que era uno de los tres directores de la Compañía South Sea y el mayor acreedor,
mandó a llamar a mi tío desde Leek a Londres,
y le aconsejó que fuera un tutor para nosotros.
Cuando mi padre falleció, tres de nosotros quedamos bajo el cuidado de su ama de llaves,
la esposa de uno de sus empleados.
Ella nos cuidó mucho, y nos educó estrictamente en la religión Protestante.
Mi hermana mayor, que era la más débil,
vivió gran parte del tiempo en el campo con mi tía,
excepto durante la época de su educación. Mis hermanos
pequeños fueron llevados a Leek por mi tía,
cuando regresaba de su visita tras la muerte de mi padre;
pero el niño no vivió por mucho tiempo.
Mi tío tenía entonces la intención de llevarme también, diciendo,
que al ver mis inocentes formas de entretenimiento, tenía un respeto particular por mí;
pero Elías Turner no lo permitió, y yo, junto con mi hermano y mi hermana,
continuamos bajo el cuidado de la ama de llaves por unos años más.
En ocasiones mi tío repetía su deseo de tenernos cerca de él,
y dejándolo a mi criterio, me mudé con él en el año 1718.

Yo había imaginado el campo como un lugar más encantador
de lo que me pareció cuando lo vi por primera vez;
y le hice saber mi descontento y desilusión a la criada que me acompañaba.
Ella se quedó conmigo hasta que regresó el carruaje, dejándome un tanto triste;
sin embargo, mis tíos se mostraron muy cariñosos conmigo,
y tuve cuidado con mis opiniones respecto a las diferencias entre el campo y la ciudad.
Pero lo que aumentó mi dolor en ese encuentro, fue el comportamiento de mi hermana mayor,
a la que no recordaba haber visto antes de que yo llegara;
ella disgustaba tanto a mi tío, que la envió lejos del pueblo,
y aunque él se esforzó por evitarlo, ella se casó con su aprendiz,
y nunca más volvió a ser admitida en su casa mientras yo viví allí.

Debido a esto y a lo tedioso de mi situación,
mi tío consideró oportuno internarme en una escuela,
aunque la razón principal no era mi aprendizaje,
pues entonces era considerada más capaz que la mayoría de los de mi edad.
En efecto, desde niña había tenido un temperamento moldeable, que como la cera suavizada,
parecía más apta para la enseñanza y la instrucción. Mi tío llegó a la conclusión
de que allí podría encontrar algo que favoreciera y distrajera mi mente,
aunque yo ocultaba mi pena lo más que podía. Me llevó donde la institutriz Hyde,
para hospedarme allí; pero en Smythy Door, Manchester,
vivía una viuda cuyo esposo había fallecido debiéndole algunas libras a mi padre,
y al pedirle mi tío el dinero y decirle de quién era hija yo,
ella le respondió que si le parecía bien, me alojaría,
y que de esa manera yo podría ir a una escuela diurna.
Mi tío indagó sobre su reputación y le consultó a un tal Nichols,
un comerciante de hilo en Deansgate, quien le aconsejó que aceptara la oferta;
diciéndome que si acaso no me sentía a gusto en la otra casa, su casa podía ser mi hogar;
y en ese lugar siempre encontré una amable acogida.

Mi tío se quedó conmigo por algunos días, y luego me dejó con la viuda y su única hija.
Disfrutaba mucho de mi nueva condición; era mucho más agradable para mí que Leek.
La viuda y su hija eran Presbiterianas,
pero mi tío había ordenado que tuviera libertad de ir a la iglesia;
cosa que ella nunca me prohibió, a pesar de que era muy estricta en su forma de adorar,
y mantenía un buen orden en su casa,
con la oración familiar por la noche y por la mañana.
Siempre participé de esas reuniones,
y aún recuerdo el placer que me producían los libros que leía entonces,
la repetición de mi catequismo, y aquellas formas de oración que se adaptaban a mi edad;
siempre teniendo en alta estima a los que consideraba religiosos.

Permanecí en Manchester hasta el final del año,
y tanto mi tío como yo pasamos agradablemente el invierno.
En la primavera él se fue para Londres,
y como mi hermana menor había sido traída de allí cuando era joven,
consideró adecuado llevarla con él para su propio beneficio,
y ella se quedó allí cuatro años. Aunque me quedé sola donde mi tío,
no sentí la ausencia de estas dos hermanas, pues en realidad eran extrañas para mí;
y mi tío me recompensó con creces al traer de regreso a mi otra hermana,
con la que había vivido bajo el cuidado de la ama de llaves.
Eso me devolvió la vida, por así decirlo, durante el mes que se quedó con nosotros,
pero su partida me afectó bastante; y mi tío,
que antes de que yo empezara a asistir a las reuniones de Amigos,
siempre procuraba hacerme feliz a su modo, se propuso llevarme de nuevo a Manchester.
Esto me agradó, y la viuda me recibió amablemente.
Ella nunca me pidió que fuera a la capilla; sin embargo,
muchas veces fui por voluntad propia,
y desde entonces he tenido oportunidad de recordar lo que viví allí. Permanecí
con ella hasta que el pueblo comenzó a dividirse entre los tory y los whig;^
footnote:[__Tory y Whig,__
miembros de dos partidos o facciones políticas opuestas en Inglaterra,
especialmente durante el siglo XVIII.]
y como ella temía las repercusiones, le pidió a mi tío que me llevara a casa.

En ese entonces tenía más de trece años,
y me había adaptado bastante al lugar donde me encontraba,
creciendo en el favor de mis tíos y en el amor hacia ellos.
Mis tíos cumplieron a cabalidad su promesa,
de que no tendría ninguna necesidad de lo que me conviniera tener;
y aunque había aprendido a bailar en Londres,
mi tío me envió donde un maestro de baile que había llegado al pueblo,
pues era un pasatiempo para el que según decían yo era apta, debido a mi agilidad;
y en efecto, me gustaba mucho.

Cuando tenía más de catorce años, mi hermano me visitó;
y puesto que mi tío siempre estaba deseando mi progreso,
me envió a aprender a escribir y a hacer repostería,
y cuando el maestro de baile regresó, me envió de nuevo a su escuela.
Esto me proporcionó un amplio conocimiento, y como había adquirido, como se dice,
un estilo diferente gracias a las enseñanzas de mi maestro londinense,
terminaba recibiendo aplausos;
algo que era muy satisfactorio tanto para mis tíos como para mí. Cuando regresaba a casa,
él solía mostrarme su afecto poniéndome en su regazo,
y preguntándome si me faltaba cierta ropa,
alguna que mis conocidas tuvieran y que yo deseaba poseer,
diciéndome que la compraría por mí; pero su amor me impedía pedir mucho,
pues apenas él veía algo a la moda me lo hacía saber.
No recuerdo haberle pedido nunca nada que me negara.

Cuando tenía más de quince años, mi tío me envió donde dos maestros de canto,
que me enseñaron a cantar salmos al compás de las notas.
Fui con muchos otros y tuve gran deleite en ello, como también en la adoración a Dios,
como había sido enseñada.

Aquí no puedo dejar de señalar,
la cantidad de invenciones que existen para desviar las mentes de los
jóvenes de las oportunidades que tienen para buscar la única cosa necesaria.
Sin embargo, fue en medio de estas actividades que comencé a reflexionar sobre el clero,
y a considerarlos dignos de doble honor; estimándolos más felices,
ya que su empleo consistía en la devoción a Dios.
Por lo tanto,
llegué a la conclusión de que tenían una ventaja
particular en los misterios de las cosas divinas,
y un conocimiento más profundo del Señor que otros.
A menudo decía, que si hubiera sido un niño, habría sido educado en la universidad,
como sucedió con mi hermano, según los deseos de mi padre.

Por esa época, algunas personas buscaban mi compañía para cortejarme,
pero no les daba ningún ánimo; porque me mantenía muy alejada de esos asuntos,
siguiendo con seriedad mis deberes como había sido enseñada,
lo que resultaba ser de gran consuelo para mis tíos.

Cuando tenía casi dieciséis, mi tío me hizo su ayudante en la familia,
y los Primeros días no solamente leía y decía los Salmos,
sino también las oraciones de la familia cuando mi tío no estaba en casa,
o se sentía de alguna manera indispuesto.
De ese modo, llegué a gozar del favor de ellos,
tanto en sus disfrutes religiosos como en los temporales.
En efecto, muchas veces he pensado que mi angustiado tío era semejante a Micaía,
de quien leemos que se consideró bendecido cuando consagró al levita como su sacerdote;
pero, ¡ay!, cuán rápido el sacerdote no solamente abandonó a Micaía,
sino que también se llevó su imagen tallada;^
footnote:[Jueces 17-18]
así que, aunque yo no robé el dios de mi tío,
rompí su paz y lo dejé contemplar la incertidumbre que produce
el deleite que se fija en las cosas temporales.

Mi tío, con la intención de que yo progresara, según dijo, dejó su pequeña casa,
aunque cómoda,
para adquirir una más grande con el fin de acomodarme
mejor a mí y a mis muchos conocidos también;
sin sospechar que la mudanza iba a arruinar su felicidad;
como sucedió. Esa casa se encontraba frente a las puertas de la iglesia, así llamada,
donde con frecuencia me era recordada la mortalidad del cuerpo, y por ello,
era impresionada con consideraciones muy serias sobre
el estado de eternidad y la inmortalidad del alma.

Como vivía tan cerca, a menudo estaba presente cuando un cadáver era llevado a la tumba,
meditando en mi corazón sobre cómo le habría ido al difunto a la hora de su muerte;
porque, aunque a menudo había escuchado al sacerdote decir esa frase:
"`Entregamos el cuerpo a la tierra,
(nótese) con la esperanza firme y segura de la resurrección a la vida eterna.`"
Sin embargo, tras la más estricta revisión,
no podía encontrar alguna evidencia de que esa esperanza permaneciera
en mí. Y aunque mis razonamientos me habían llevado a concluir,
que se trataba de un don de Dios dado directamente al alma en el momento de la partida;
y mi aprecio por el clero,
me llevaba a la creencia de que se trataba de una
certeza que les había sido concedida a ellos,
y que las personas debían basar su esperanza en eso; aun así, mi inquietud no se calmaba,
ya que ese fundamento se estaba sacudiendo tanto que mi fe no podía apoyarse en él,
y continuaba angustiada.
Pero aunque era un misterio muy grande para mi entendimiento natural, y por tanto,
imposible de comprender, aun así,
consideraba que era necesario que un Cristiano encontrara
esa esperanza mientras estaba sano,
para soportar mejor su enfermedad y para que lo ayudara
a someterse a la voluntad de Dios en su muerte.
Durante ese tiempo mi alma se encontraba bajo una fuerte presión,
y aunque en ese momento ignoraba la causa,
desde entonces he creído que eran nada menos que las persuasiones del amor del Padre;
pero como el hombre natural no percibe las cosas que son de Dios,
no sabe dónde buscarlas.
Creyendo que aún me faltaba de ese celo que veía en otros,
me mostraba cada vez más ferviente en mis oraciones,
añadía más cosas a mis devociones privadas,
y asistía con diligencia a mis devociones públicas; y algunas veces,
continuaba con empeño la repetición de esos ejercicios.

Cuando tenía unos diecisiete años,
un obispo llegó al pueblo para realizar la confirmación,
lo que consideré de gran beneficio para mí;
porque pensé que a partir de esa ceremonia se apoderarían
de mi alma una esperanza y una fe más firmes en Cristo,
y creía que había un poder extraordinario dado a ese alto y santo cargo,
del que iba a recibir algo de la naturaleza divina.
No dudo que el Ser Invisible miró con compasión el ferviente deseo de mi alma,
y vio con aceptación el temor reverencial en el que mi mente, así como mi cuerpo,
se postraron para recibir las primicias de mi anhelo; y sé que mi comportamiento,
tanto antes, durante y después de ese momento,
no pasó desapercibido para mis parientes e íntimos.

Poco después, mi tío me preguntó sobre lo que pensaba acerca de recibir el sacramento.
Le dije que no creía que fuera conveniente que personas tan jóvenes lo hicieran;
porque según se decía: "`Los que lo reciben indignamente,
se aseguran para sí la condenación,`" y no me atrevía a recibirlo.
Me habló de algunos que eran tan jóvenes como yo,
y que él consideraba que no eran más aptos.
Yo le dije que lo sabía,
pero que ellos parecían exaltarse a sí mismos entre sus amigos a causa de eso,
de lo que yo no me atrevía, con la mayor humildad, a participar;
ni tampoco encontraba que mi fe fuera lo suficientemente madura
para comprender el misterio entre el pan y el vino externos,
y el cuerpo y la sangre de Cristo.

Aquí comencé a flaquear en mis esperanzas de haber sido
beneficiada por la imposición de manos del obispo.
¿Y qué si dijera, que dudaba no de una o dos cosas,
sino de todo lo que había hecho por causa de la religión?
¿Acaso pensaba que Dios no existía? Oh,
no; sino que para mi inexpresable dolor, no podía encontrar la manera de adorarlo,
como para probar mi aceptación, o la seguridad que anhelaba,
ni mi alma podía descansar sin ello.

Me había esforzado en mis propias ideas, agotado todas mis esperanzas;
y como una persona realmente cansada, al sentarme, se me hizo soportar tal humillación,
como nunca antes había experimentado;
viendo que me alejaba de aquello que yo consideraba lo más beneficioso para mí,
y que mis prácticas religiosas no eran más que un montón de comodidades pasajeras,
que se desvanecían continuamente en su ejecución. Al final, seguía con tanta pesadez,
que comencé a cansarme de ellas,
y a querer dejar la carga que había asumido en mi propia voluntad.
Encontré que eran demasiado para seguir avanzando con ellas,
pues descubrí que las había obtenido solamente por tradición.

Este fue un tiempo difícil,
en el que me encontraba lejos de cualquier tipo de exaltación,
pues me resultaba difícil avanzar sin fe,
la que ahora comprendía como un don directo de Dios.
Bajo esta convicción clamé como el pobre recaudador de impuestos: "`¡Dios,
ten piedad de mí!`"; y mi alma se sintió más justificada por esos respiros,
de lo que jamás se había sentido en todas las desgastantes tareas que había realizado.
Pero el enemigo, que siempre está cerca para ahogar el bien en nosotros,
me perturbaba con sus muchas insinuaciones,
como la idea de que realizar la debida adoración a Dios por sus favores,
nunca podría ser el camino para alcanzar la felicidad.
Sin embargo,
cuánto más cedía a los pensamientos de rendirme ante la misericordia de Dios,
más encontraba una esperanza brotando dentro de mi alma,
de que el Señor me mostraría un camino.
Eso me alejó aún más de todas las ceremonias,
y desvió a tal punto mi mente de los entretenimientos en los que solía deleitarme,
que mis tíos se dieron cuenta de ello y lo llamaron melancolía.
Pero esto era producto de una profunda reflexión,
sin saber de qué manera o por qué camino debía ser dirigida;
cómo iba a recobrar el verdadero sentido de mis aflicciones,
o cómo obtendría una seguridad satisfactoria.
Mis tíos se esforzaron mucho para detener este pensamiento melancólico,
y le pidieron a mis conocidos que me visitaran más a menudo; pero sus frecuentes visitas,
no eran de mi agrado.
Esas noches derrochadas en lo que antes consideraba diversiones inocentes,
se convertían en mañanas pesadas; y mi deseo de estar sola,
junto con la fatiga de tanto apuro, me hacía pensar en evadir tales situaciones.
Por lo tanto le pedí a mi tío que me dejara trabajar como sirviente,
pero ellos no quisieron ni contemplar la idea de separarse de mí.

Cuando tenía más de dieciocho años, escuchamos de que S. Taylor, una Amiga,
estaba a punto de vender los artículos de su tienda, y que se iba a vivir a Stafford;
y yo le solicité a mi tío que los comprara para mí,
pensando que ese empleo podría aliviar la incertidumbre en la que me encontraba.
Yo era entonces una extraña para ella, y mi tío,
que siempre estaba dispuesto a complacerme,
y a quién le gustó mucho más esta propuesta que la primera, la mandó a llamar;
y al poco tiempo, acordó que yo tuviera la mercancía,
y que me quedara de vez en cuando con ella para familiarizarme
con el negocio y con los clientes.
Así fue como esa familia y yo nos conocimos por primera vez, aunque en ese momento,
no tenía la menor idea de que alguna vez cambiaría
mi nombre por motivos de religión. De ahí pues,
muchos imaginaron que comenzó mi creencia, a la cual me referiré en el momento adecuado.
Yo iba a mi tienda según lo acordado,
sin permitir que vieran el ejercicio en que aún me encontraba;
ni tampoco noté nada extraordinario en mis nuevos conocidos,
pues sus ejercicios se mantenían ocultos al igual que los míos.

Cuando llegó el momento de incorporarme a la tienda,
mi tío dejó a S. Taylor encargarse de toda la valoración de los bienes del lugar,
debido a la buena opinión que tenía de los Cuáqueros.
Continué viviendo con mi tío,
y me propuse como norma regresar a casa inmediatamente
después de cerrar la tienda por la noche,
esquivando así a mis viejos amigos.
Pasaba el día en el negocio, y parte de la noche sumida en mis pensamientos;
el deseo de mi alma crecía en pos del resurgimiento de la esperanza, lo cual,
como mi poca fe en lo que se consideraba el servicio de Dios seguía disminuyendo,
encontraba que a veces me acercaba más a una confianza en Él,
y a esperar pacientemente lo que pudiera ocurrir.

Cuando tenía unos diecinueve años, recibimos la noticia de la muerte de mi hermana Lydia,
por lo que nuestra familia estaba de luto;
y yo no sólo guardé luto en mi forma de vestir, sino también en mi corazón;
porque la amaba más que a cualquier otra hermana, y verdaderamente puedo decir,
que su muerte añadió carga a mi ejercicio,
así como a mi creencia de que era necesario hacer firme mi elección. ¡Oh!,
la angustia en la que me encontraba, cuando me veía a mí misma, y veía a los demás,
y los contemplaba avanzando con alegría en los respectivos deberes de su religión,
y que yo, no sólo me encontraba estéril en mis deseos de ella,
sino tan oprimida en el cumplimiento, que no podía apoyar a mi tío,
ni a mí misma de esa forma.
Los que están familiarizados con la naturaleza caída,
pueden formarse una mejor opinión de mi estado, cuando mi tío,
que solía mostrarme tanta indulgencia,
me hacía saber su felicidad por mi buen comportamiento,
al decir que difícilmente podía estar en compañía de alguien sin que me elogiaran.
En realidad, era algo muy placentero para mi amable tío, quien me dijo un poco después,
que quería que fuera prudente; "`porque,`" dijo, "`hay ojos puestos sobre ti,
de los que no te das cuenta.`"

Creo que en ese entonces,
él consideraba que estaba a punto de ser recompensado
en sus aspiraciones con respecto a mí,
que eran, verme felizmente establecida en el mundo.
Y creo que en aquel tiempo,
los padres de mis amigos tenían por lo general respeto hacia mí;
porque aunque yo era de un temperamento enérgico y vivaz, aun así, por la bondad de Dios,
fui resguardada de lo inmoral o de lo profano,
y me mantuve dentro de los límites de lo que se consideraba
una conducta inocente y una buena crianza.
Esto animó a muchos que tenían hijas a que fomentaran una amistad conmigo.
¡Pero cuán rápido vi un cambio!
Porque lo que debería haberme elevado en su estima,
pronto se convirtió en la causa de su desprecio.
Es muy cierto, que el mayor agrado, una vez transformado,
demuestra ser el mayor desagrado.
Pero para continuar; no podía seguir bajo la nube de insensibilidad,
porque la Aurora me había visitado desde lo alto, y el velo se había rasgado tanto,
que vi que la obra de Dios era en lo secreto de mi corazón,
y que allí debía establecerse la adoración espiritual.

Entonces recordé que había escuchado a los Cuáqueros animar
a las personas a volverse a ese don de Dios en sí mismos,
y a seguir las enseñanzas del Espíritu.
Pensé que esto se acomodaba muy bien a mi condición,
y mi mente se vio obligada a reconsiderar su doctrina.
Entonces, como no quería que se fijaran en mí,
salía como si fuera a caminar durante el tiempo del servicio.
Este ejercicio era permitido por los más estrictos,
para eliminar cualquier somnolencia que pudiera aferrarse a la mente,
incapacitándola para sobrellevar las devociones de la tarde.
Aunque yo no tenía una verdadera necesidad de esto, siendo alguien de buen ánimo,
ya que antes de conocer la falta de fe en mi manera de adorar,
era celosa en mis devociones, vivaz en mis entretenimientos y diligente en mi trabajo;
aun así, me tomé esta libertad, pues la reunión de los Cuáqueros estaba en mi camino,
y tenía la intención de informarme acerca de ella,
haciendo una parada al pasar por la puerta.
Si no oía ninguna voz, me marchaba en seguida;
pero si alguien hablaba entraba por la puerta, por un pequeño extremo,
considerándolo un buen lugar para refugiarme de las miradas de los que estaban
sentados en el salón de la reunión. Hice estas visitas tanto como pude;
y ciertamente puedo decir, que el Señor fue muy misericordioso,
y que me dio un entendimiento más claro del que jamás
había encontrado dentro de mí en las otras reuniones;
y como nuestra casa estaba muy cerca, tuve oportunidad de hacerlas.
Mis intenciones con respecto a estas libertades eran buenas,
y solía quedarme tanto como me atrevía, luego me desviaba por el siguiente campo,
y me dirigía de nuevo al lugar de mi adoración. De este modo comprobé
el efecto que producían las diferentes doctrinas en mí:
La primera respondía a la esperanza de esa justificación de la que hablé anteriormente,
y la última era infructuosa e insípida.
Sin embargo, seguí tanto en la repetición de estas pruebas,
que vi claramente que lo mismo que sucedía conmigo,
les sucede a los que les cuesta creer eso que no quieren que sea verdad;
pero la verdad y la misericordia de Dios me siguieron tan de cerca,
que encontré un juicio dentro de mí del Todopoderoso,
por empeñarme en lo que no me daba la menor satisfacción. Con gusto habría permanecido
en esa antigua profesión religiosa en la que había sido criada desde mi niñez,
y que era tan grata para mis deseos naturales como lo había sido Ismael para Abraham;
pero vi que no debía permanecer,
y por lo tanto hice un alto y me negué a ir a la iglesia, así llamada.

Yo le había manifestado algo de mi inquietud a mi hermana,
quien había regresado de Londres,
y ella le dijo a mi tía que yo era simpatizante de los Cuáqueros,
y que no tenía intenciones de ir a la iglesia nacional.
Esto la enfureció bastante, y me dejó diciendo,
que iría a buscar al párroco y a la gente para que me llevasen.
Pero la verdad había obrado a tal punto en mí,
que descubrí que no sólo debía aventurarme a eso,
sino que además debía luchar en contra de la resistencia que sentía en mí misma.

Pasé la siguiente noche más confundida de lo usual,
y al día siguiente mis tíos fueron donde el párroco, y al poco tiempo me mandó a llamar.
Me miró con asombro,
queriendo manifestar su gran error con respecto a alguien que consideraba tan religiosa,
y tan buen ejemplo para otros; pues yo asistía constantemente a los días llamados Santos,
así como a otros días señalados para la adoración.
Me preguntó desde cuándo me sentía inquieta;
le dije que desde hacía mucho tiempo,
y que no podía encontrar ninguna satisfacción verdadera en nada que pudiera hacer.
Me expresó que la perseverancia en los deberes que me habían enseñado era la única forma,
y que sin duda alguna, me llevaría a la satisfacción de la que hablaba.
"`Pero,`" dijo, "`tu tío teme que te hagas Cuáquera.`"
Yo le respondí: "`No creo,
aunque he encontrado una medida de satisfacción en su predicación,
que jamás he encontrado en otro lugar.`"
Él dijo que no era más que un engaño del gran enemigo de nuestras almas;
y luego expuso lo peligroso que era que los jóvenes los escucharan o leyeran sus libros,
afirmando que sus principios eran seductores y erróneos,
y quiso que le prometiera que no los oiría más.

Dijo muchas cosas fuertes acerca de ellos,
y me preguntó particularmente sobre la familia de los Taylors;
pero pude exonerarlos honestamente de cualquier culpa en este caso,
y le dije que ni ellos ni ninguna otra persona,
habían intentado siquiera insinuar sus principios,
o hacerme cambiar de una persuasión religiosa a otra.
Entonces me dijo que si yo desistía de oírlos y de leer sus libros, me iría bien,
y que si continuaba con mis deberes y con una buena compañía,
podría sobreponerme a mi inquietud.
De hecho,
dijo tanto en contra de la persuasión de los Cuáqueros que mi respeto por el clero,
junto con mi indiferencia por las formalidades (como yo
entonces solía llamar a las costumbres de dicho pueblo),
me determinaron a no volver a oírlos nunca más. Dije (y muy sinceramente),
que nunca me convertiría en Cuáquera, si podía evitarlo;
ni lo fui hasta que el deseo de paz de mi alma no
pudo encontrar satisfacción de otro modo;
y nadie luchó tanto como yo para escapar de ello,
como se muestra en el siguiente relato.

Tales eran entonces mis razonamientos infantiles,
que aunque había sido testigo de la obra de Dios en medio de ellos,
pensaba que si llegaba a poseer lo que ellos predicaban,
y que percibía como olor grato en mi corazón,
no importaría si seguía o no cualquier forma de adoración.

Mi tío dijo que el párroco, que se llamaba Leay, me hospedaría,
cosa que le parecía adecuado a mis tíos. Yo entendí sus intenciones y le agradecí,
pero le dije que eso sólo le daría al pueblo razones para
creer que había habido una diferencia entre nosotros,
y que si ellos se tranquilizaban,
yo vería qué podía hacer en cuanto ir a la iglesia de nuevo.
Sin embargo, recuerdo muy bien lo difícil que fue esa prueba;
y seguí con tanta indiferencia, que les causé una gran inquietud a mis tíos,
y a mí también.

En poco tiempo, el párroco Bennet me envió a llamar por medio de la viuda Brueton;
y él también expresó lo sorprendido que estaba de
haberse equivocado tanto con respecto a mí,
diciendo que de haber ocurrido lo mismo con otras personas,
no se hubiera sorprendido tanto.
Como éramos muy parecidos y también cercanos,
podía actuar con mayor libertad con él. Me preguntó si pensaba convertirme en Cuáquera,
yo le dije: "`No lo sé, pero creo que no.`"
"`Porque ellos niegan las Escrituras`", añadió. Yo le dije: "`Si lo hacen,
te prometo que nunca me uniré a ellos, pero sé que no lo hacen.`"
"`Bueno,`" dijo, "`las tergiversan para su propia destrucción;
y niegan el bautismo`". Le dije: "`Niegan el de agua, pero predican el bautismo.`"
"`Sí,`" dijo,
"`y uno muy extraño también. Pon tu dedo en ese fuego (uno que
había en la habitación,) y ve cuánto puedes soportar ese bautismo.`"
Esto llenó mi mente de indignación, y le dije: "`No, lo rechazo;
pues creo que ellos no se refieren más al elemento natural del fuego,
como tampoco se refieren al bautismo en el elemento natural del agua.`"

Puedo concluir que en aquella época ni él, ni yo,
conocíamos ese misterioso bautismo que mi alma,
desde entonces ha experimentado en ocasiones.
Él continuó hablando con soltura de los principios de los Cuáqueros,
calificando algunos de ellos como bastante ridículos, y diciéndome que si no le creía,
me prestaría algunas de sus obras.
Le di las gracias,
diciéndole que no estaba dispuesta a leer los argumentos de ninguna profesión;
y ciertamente no lo estaba, pues incluso las Escrituras mismas,
en las que había estado tan versada y me había deleitado tanto,
en aquel momento me parecían de poco provecho;
y mi separación de todos mis deberes religiosos era tal,
que no podía confiar en nadie más que en Dios.
Pero volviendo a lo anterior, le dije: "`No puedo juzgarlos por sus escritos,
pero estoy segura de que al menos están en lo cierto al afirmar,
que como Dios es un Espíritu,
debe ser adorado en espíritu y en verdad`". No dijo mucho después, sólo:
"`Si ya tienes una noción del Espíritu, se te acabaron las esperanzas.`"

Desde entonces, el malestar de nuestra familia dejó de ser un secreto; mis amigos,
uno tras otro,
me acosaban con el nombre de "`bonete`" y "`Amiga,`" o me preguntaban burlonamente:
"`¿El Espíritu te mueve?`"
Esta, junto con otras burlas, golpeaban mi inclinación natural.
La tormenta se volvió más furiosa, tanto interna como externamente;
con mis conocidos fuera de la familia y con mis allegados en casa.
Pero por encima de todo eso, los enemigos de mi propia casa,
que estaban siempre listos en cada dificultad que se me presentaba,
a inclinar la balanza contra mi pequeña esperanza,
e insinuar la necesidad de ser cautelosa y reflexiva en mis decisiones,
habían hecho tanto para intentar que siguiera por el camino en el que había sido enseñada,
que los justos juicios del Todopoderoso se apoderaron nuevamente de mi alma,
y de una forma tan fuerte, que hicieron que ese corazón,
que solía saltar de alegría al repicar de las campanas, ahora temiera.
Esa alma que solía acercarse a la casa consagrada con reverencia,
ahora temblaba en la entrada;
y esos pasos que solían avanzar hacia el banquillo con deleite,
perdieron su efecto anterior; y nada más que horror y oscuridad aparecían en el aposento,
donde una vez se habían levantado deliciosas ofrendas de oración y alabanzas a Dios.

¡Oh!
Ciertamente puedo recordar suficiente con respecto a este punto,
sin necesidad de detallar las aflicciones que me produjo el ferviente
deseo de mis amables tíos por mi bienestar eterno.
Así lo creía, y por lo tanto me esforcé en soportarlas en sumisión y rendición,
como si procedieran de un principio de amor.
Verdaderamente hice todo lo que estaba en mi poder para aliviar
la angustia de mis tíos. La pérdida de su descanso y apetito,
y el desasosiego de sus mentes, me causaban un gran dolor; por lo cual,
el poco consuelo que podía encontrar dentro de mí era, que yo no era la causa de ello,
más allá del hecho de que deseaba tener el "`testimonio de una buena conciencia delante
de Dios,`" y una seguridad de lo que podría sucederme más allá de la tumba;
pero no podía encontrar dicha seguridad en la angustiante
situación de mente en la que me encontraba.
No obstante, yo anhelaba en secreto volver a oír a los Cuáqueros;
pero como mi tío me vigilaba muy de cerca para que
yo no tuviera la oportunidad de satisfacer mi deseo,
debo reconocer como un favor especial,
que por ese tiempo llegó a visitarnos una joven de Newcastle.
Ella desconocía nuestra angustia,
y como mi mente seguía urgida por oír a los Cuáqueros (como ya se ha dicho),
la llevé afuera, como para caminar, y cuando estábamos cerca del lugar de reunión,
le pregunté si quería oír a los Cuáqueros: "`Sí,`" me respondió,
"`porque no hay ninguna reunión de esas personas en nuestro pueblo.`"
Estoy segura, de que si ella hubiera sabido algo de nuestra angustia familiar,
hubiera podido leer la confusión en mi rostro cuando le hice la pregunta,
y mucho más cuando entré por la puerta y oí sobre
la desventaja de los que se debatían entre dos opiniones.
El ministro demostró, a partir de las expresiones del apóstol,
que "`el hombre de doble ánimo es inconstante en
todos sus caminos;`" y al proseguir con esa doctrina,
mi esperanza y mi fe fueron renovadas,
al ver que el Señor seguía siendo misericordioso conmigo.
Yo había experimentado al testigo de Dios puesto en el corazón,
del que hablaban varios Amigos; sin embargo,
ese inesperado testimonio se adecuaba tanto a mi circunstancia del momento,
y respondía tan bien al ferviente deseo de mi mente de ser
dirigida en el camino que me guiaría al favor de Dios,
que por medio de eso, y del hecho de que no nos conocíamos,
todos los prejuicios fueron quitados, y así me afiancé en mi nueva profesión. Porque,
aunque no me uní inmediatamente a la Sociedad,
puesto que tenía que reunirme con alguna comunidad,
me pareció que debería estar con aquellos cuya doctrina había alcanzado mi alma;
con la firme determinación y la buena intención de no persistir
ni un instante más en un camino en el que no tenía fe,
sino de someterme a la voluntad del Todopoderoso,
y de seguir eso que me destetaba de depender de la adoración formal.

Volvimos a casa; ella satisfecha por haber complacido su curiosidad,
y yo también por la intervención de la Providencia en este asunto;
ambas llenas de admiración, ella por la rareza de los Cuáqueros, y yo por su doctrina;
muy parecidas a las dos mujeres en el molino, una tomada con la verdad y la otra dejada.
Yo podría haber ocultado dónde habíamos estado, pero ella no.
Mi tío fue informado de eso,
pero no hizo ningún comentario al respecto mientras ella estuvo allí; pero cuando se fue,
mi tío se embriagó como hizo en otra ocasión, para poder darle rienda suelta a su furia;
de otro modo,
difícilmente lo habría llevado más allá de su razón como para tratarme como lo hizo.
Pues según sus propias palabras,
él había buscado oportunidades de castigarme cuando era niña,
pero no había encontrado ninguna falta en mí que
le diera una razón suficiente para hacerlo;
pero en ese momento creía que no había nada más cruel
que permitirme avanzar hacia mi propia ruina,
tanto del cuerpo como del alma.

Por aquel tiempo yo había rechazado a un joven, que según mi tío, me haría feliz;
él me había ofrecido una renta considerable, y mi tío había ofrecido, muy generosamente,
adelantarme cien libras,
además de lo que yo poseía. Pero cuán diferentes eran nuestras posturas;
mi tío se preocupaba por proveer para mi bienestar físico,
y yo estaba más preocupada por el bienestar de mi alma;
pues no podía pensar en un deleite mayor que el del favor de Dios,
y sentí que debía prepararme para sufrir por causa de ello,
ya que veía que se oponía a sus propuestas.

Mi tío, como he mencionado, tras haber bebido mucho se comportó de manera violenta;
aunque yo pude encubrirlo todo en cuanto a sus intenciones,
salvo una expresión temeraria que se le escapó al término del caos de esa noche;
y que menciono para exponer la razón por la cual los dejé,
así como para dar una idea de cómo me fue.
Él dijo que si yo alguna vez volvía a la reunión, me quitaría la vida.
Yo temblaba, sin embargo, recibí la amenaza en un estado tierno de mente,
y pude percibir que se lamentó de lo dicho al instante.
No estaba muy preocupada por mi vida,
ni podía creer que mi tío llevaría a cabo su palabra, pero, ¡ah!,
la idea de separarnos abrumaba mi mente con dolor,
porque en ese momento descubrí que no me atrevía a retroceder
ante la verdad que había impactado mi mente,
ni podía pensar en dejar a mis parientes más cercanos de esa manera.

Se agitaron muchos pensamientos dentro de mí y derramé muchas lágrimas,
bajo la consideración de mi infeliz circunstancia, como entonces la llamaba.
El enemigo de mi alma manifestó su enemistad,
al sugerir cuán improbable era que yo obtuviera alguna victoria sobre mi yo,
o mis parientes; y que mis precipitadas acciones podrían ocasionar una masacre.
Pero mi alma tiene que dar testimonio de la misericordia de la Divina Bondad,
la cual me infundió en ese humilde estado, algo de ánimo; y prevaleció el deseo,
aunque no lo busqué, de restablecer mi poca fe oyendo de nuevo la Palabra más penetrante;
y concluí que sería mejor, para calmar la ira de mis tíos,
volver directamente a mi propio apartamento al terminar la reunión,
el cual estaba amueblado con una cama y unas pocas cosas
necesarias que yo había comprado con el ingreso de la tienda.
Guardaba la esperanza de que verían lo que hacía con buenos ojos,
y que cuando se les pasara un poco el disgusto, me mandarían a llamar a casa.

No se dieron cuenta de mi ausencia hasta que llegué de esa reunión,
y consideraron conveniente que me quedara donde estaba hasta la siguiente
reunión. Entonces enviaron a una persona para ver si yo estaba allí,
pero no había sentido ninguna necesidad en mí de ir en esa ocasión,
ni durante algunas semanas después;
ni estaba tan entusiasmada con esta "`novedad,`" como lo llamaba mi tío,
como para forzar mi inclinación en lo más mínimo;
porque si hubiera creído la idea de que uno puede servir
a Dios aceptablemente sin asistir a alguna adoración pública,
con facilidad habría podido permanecer separada de todos.
Sin embargo,
este tiempo de deliberación dio ánimo y una excusa
para que mis viejas amistades me visitaran por turnos.
Los más jóvenes para mostrar su astucia,
reprochando lo que ellos llamaban los principios de los Cuáqueros; y los más serios,
para exponer, según sus conceptos,
lo que ellos llamaban las doctrinas diabólicas de ese pueblo.
Me quedé muda, sintiendo muy poco que decir en respuesta;
solamente en ocasiones daba a entender que su doctrina hablaba de mejores cosas;
pero como entonces no había adquirido conocimiento por medio de sus escritos,
no me atrevía, ni deseaba esforzarme por defenderlos.

Mi mente, ciertamente, no se había inclinado hasta entonces,
a consultar ni a los hombres ni a los libros,
para no ser seducida a creer lo que no era de Dios;
porque claramente había visto que nada que no fuera de Dios podría satisfacer mi alma.
Puedo decir, con agradecimiento a ese Poder Eterno que aún me guardaba,
que los argumentos expuestos no disminuyeron mi anhelo del alma en busca del favor divino;
y aunque espero nunca haber sido sabia en mi propia opinión, aun así,
la verdad de Dios se exaltaba a tal punto en lo secreto de mi alma,
que podía experimentar que sus influencias eran más sabias que todos mis maestros,
que con sus mejores argumentos, eran como el martillo al clavo,
al fijar en mi alma las impresiones que había recibido.

Mi tío también me visitó en esta situación, la severidad de su semblante había cambiado.
Me hizo saber con amabilidad lo difícil que era para ellos el habernos separado,
y que si me comprometía con la promesa de que nunca me convertiría en Cuáquera,
él me daría una escritura de herencia,
para que cuando él y mi tía fallecieran yo obtuviera todo
lo que tenían. Yo le contesté que si pudiera hacer tal promesa,
no habría un mayor estímulo que la continuación de su amor; pero ¡oh!,
que no podía hacerla.
Ambos nos sentamos y lloramos nuestro dolor.
Mi tío mencionó que yo los había dejado de manera muy abrupta;
pero en lugar de invitarme a casa,
me dio a entender que entonces ya no podía alegrarse de verme sin que yo cambiara
de opinión. Pero en poco tiempo encontré el bálsamo de la Eterna Bondad,
que sanó la herida que mi mente había tenido que soportar a causa de la verdad.

Entonces llegó a visitarme un joven que había sido un estudiante,
y que había recibido órdenes junto con una comisión; no era uno de los más considerados,
como se verá. Tras hacerme el cumplido de: "`Señorita, ¿cómo está usted?`",
y yo de agradecerle, me dijo: "`¿Sabe usted que escuché que se está haciendo Cuáquera?`"
Yo le dije: "`Algunas veces oímos cosas que no son del todo ciertas;
pero me imagino lo que vas a decir.`"
"`Pues entonces,`" dijo, "`tiene que haber habido un gran cambio en usted;
muchos sollozos y suspiros, y mucho uso del tú y del ti.`"
"`Y dime`", le respondí, "`¿qué tienes tú en contra de ese lenguaje?`"
"`Pues,`" dijo, "`no corresponde a la moral, ni a la cortesía común;
sino que se usa entre los hombres y sus bestias,
y es más apto para ser usado con los bárbaros que con los hombres.`"
Yo le respondí: "`Siento mucho que pienses así; pero recuerdo y sé,
que ese mismo lenguaje es el que usamos en todas nuestras oraciones y letanías,
cuando elevamos nuestras peticiones; por lo tanto, ten cuidado con lo que dices,
porque cuando dices que es apto para ser usado sólo con las bestias y con los bárbaros,
¿en qué conviertes entonces a tu Dios?`"
"`Oh,`" dijo, "`puedo percibir que estás del lado de los Cuáqueros.`"
"`Sí, lo estoy,`" le dije,
"`en cuanto a creer que el lenguaje que usamos para honrar
a Dios es lo suficientemente bueno para el hombre.`"

Él se marchó; y no pasó mucho tiempo sin que mi tío me visitara por segunda vez.
Como entonces él consideraba que yo estaba en un estado de confusión,
e indecisa de a quién unirme, me propuso la religión de los Presbiterianos,
diciendo que me daría su consentimiento para unirme a ellos.
Pero por la experiencia que había tenido con esas personas
durante las dos ocasiones que había estado en Manchester,
sabía que ellos se ocupaban mucho de las mismas cosas que yo solía practicar;
por lo tanto era muy improbable que yo encontrara en ellos la satisfacción que buscaba.
Mi tío también me propuso quedarse con la tienda y asumir la pérdida
que él podría tener por la venta de todos los bienes,
si yo elegía otro lugar para hospedarme en cualquier otra ciudad;
pues él pensaba que si me alejaba del camino de la vergüenza y desgracia (como él lo
llamaba) podría ser un medio para que yo cambiara mi resolución. Pero la creencia de
adoración espiritual que había concebido estaba tan grabada en mi mente,
que me parecía que debía llevarla conmigo,
aunque me trasladara al último rincón del planeta.
Le hice saber esto; y él, asombrado de mi insensatez, me dejó diciendo,
que sin duda alguna yo estaba hechizada.
Ciertamente, en ocasiones,
yo misma reflexionaba sobre qué era lo que sostenía mi alma
contra las muchas afrentas que recibía de los demás,
y contra las secretas tentaciones que eran presentadas diariamente a mi mente,
abrumándola hasta el punto, de que en el poco dormir que tenía,
frecuentemente soñaba algo relacionado con mis ejercicios.

En uno de mis sueños apareció un hombre que llegó
a mi puerta con una zaranda en su mano y una bolsa.
Se sentó, y al abrir la bolsa, puso un poco de trigo en la zaranda.
Yo le pregunté qué iba a hacer; me dijo: "`Separar la granza del trigo.`"
Aquí el enemigo disparó su dardo envenenado contra aquel temor que se alojaba en mí,
y a través de sus insinuaciones me hizo creer que yo era la granza,
arrancada de mi previa tranquilidad,
por aspirar al conocimiento de cosas demasiado elevadas para mí. ¡Oh!
La aflicción en que se hallaba mi alma,
a causa de esos asaltos del enemigo que traían a
mi memoria los fracasos de mi vida y mis tontas acciones,
como múltiples testigos contra mí;
mientras yo me esforzaba por resistirlo con arrepentimiento y promesas de enmienda,
razonando conmigo misma los buenos motivos de mi presente proceder.
Pero como no tenía la evidencia de la esperanza a mi disposición,
me vi obligada a sufrir hasta que fuera nuevamente revivida por
las misericordias de un Dios que no quiebra la caña cascada,
ni apaga el pábilo que humea.

En ese lapso, mi tío llegó nuevamente con el párroco Leay,
todavía con la esperanza (por haber permanecido en casa) de que podrían convencerme;
pero se dieron cuenta de su error, porque aunque dije muy poco,
estaba dispuesta a probar la verdad como nunca antes.
Nos sentamos,
y el párroco se ofreció a poner por escrito todos los escrúpulos que yo tuviera,
comprometiéndose a responderlos él mismo,
o pedirle al obispo que los respondiera él. Les agradecí su amabilidad,
diciéndoles que no veía cómo alguien podía ser de beneficio para mí,
pues lo que en realidad necesitaba era fe.
Me dio a entender que no le correspondía a los ignorantes
entrometerse en los asuntos de la fe,
sino creer según los cánones de la iglesia;
y continuó elogiando en gran manera la sabiduría
y el gran cuidado que habían tenido los sabios padres,
para que no existieran defectos ni errores en los artículos de nuestra fe;
concluyendo de ahí que era necesario que los creyéramos.
Le di a entender que yo no podía depositar mi confianza en el hombre,
pero que ya había recibido una mejor fe,
y que consideraba que debía buscar a Dios por mí misma.
Él me dijo: "`Eres terca, y si no tienes cuidado, renunciarás a tu voto de bautismo.`"
Yo le respondí: "`No veo que eso me inquiete; pues lo considero un asunto irrelevante,
que no me beneficiará ni me perjudicará.`" Él dijo: "`Te has endurecido; y si persistes,
serás condenada.`"
Esto nos dejó en silencio; y tan pronto como quité mi mirada de él,
la puse sobre mi querido tío, cuya mirada mostraba claramente su dolor.
El párroco se levantó y dijo: "`Necesitas las plegarias de la congregación.`" Yo le dije:
"`Sé que necesito las oraciones de todas las personas buenas, y deseo tenerlas.`"
Cuando salieron de la tienda, lo oí decir que yo me encontraba bastante perdida,
y mi tío asintió, y con mucha tristeza me dejó.

Esa fue una gran prueba para mí,
porque el enemigo dirigió nuevamente su dardo para herirme con un golpe fatal,
insinuándole a mi mente la doctrina de la elección y la condenación;
lo que reforzó las dudas suscitadas en la última conversación.

¿Qué podía hacer yo?
¡Sin nadie en el mundo a quien huir,
a quien poder encomendar mi alma! ¡Sin un libro para confirmar mi causa,
pues la misma Biblia era como un libro escrito en una lengua
desconocida! ¡Sin un Dios o un Salvador a mano,
ni siquiera ningún consuelo del que yo fuera consciente!
Lean en estas expresiones, las profundas angustias de mi alma,
que yacía bajo los pisotones del más despiadado enemigo.
Si yo hubiera podido encontrar una verdadera razón
para sus acusaciones sutiles contra mí,
sin duda habría aparecido en ese momento;
o si hubiera podido creer que Dios era injusto y
que infligiría el castigo eterno a los inocentes,
o a un pecador arrepentido que estuviera dispuesto a apartarse de todo camino perverso;
yo digo, si hubiera podido conciliar esto con Sus atributos de misericordia y bondad,
sin duda habría caído ante las insinuaciones del cruel engañador,
que en ese momento se apareció de la manera más insólita; causándome ese ejercicio,
que hasta el día de hoy me causa asombro.
Porque una noche, mientras estaba acostada en la cama, me pareció oír de repente,
una voz audible como la mía, que maldecía al Señor y desafiaba al Cielo, diciendo:
"`Ahora estoy condenada,
porque he pecado contra el Espíritu Santo y nunca seré perdonada.`"
Después de oír estas palabras, me sentí desconcertada,
e inmediatamente me arrojé sobre mi rostro y clamé: "`¡Oh Señor, perdóname!;
pero no he sido yo, sin embargo, ¡Señor, perdóname!`"
Así continué, confundida; en ocasiones implorando perdón,
y luego negando que había sido yo;
y cuando me recobré lo suficiente como para saber mi condición,
encontré que estaba completamente empapada de sudor,
debido a la agonía. La cama donde estaba acostada se sacudió por cierto tiempo,
debido a mi fuerte temblor;
y transcurrió un tiempo considerable hasta que finalmente logré tranquilizarme.
Sin embargo, cuando pude hacerlo, encontré que mi grandioso Dios no me acusaba;
sino que alentaba mi sincero deseo de verlo como el Dios que salva
misericordiosamente a los que confían en Su providencia,
y que está dispuesto a perdonar las transgresiones pasadas del verdadero penitente.
Aquí encontré que mi esperanza se renovaba y que mi fe se afianzaba; sin embargo,
incluso aquí tropecé con el honor que me habían enseñado
a darle a los oráculos divinos (como yo estimaba al clero),
y pensé que seguramente me equivocaba al suponer que en
ellos no había más que en el resto de los hombres;
tampoco fui capaz de desestimar su erudición,
y colocar a los analfabetos (como me habían enseñado a llamarlos) en el mismo
nivel de sabiduría que los que tenían el sublime título de "`reverendo.`"
Pero aquí mi Dios me ayudó; porque una noche,
mientras permanecía sentada bajo un estado humilde de mente, meditando a solas,
la Verdad eterna se apoderó de mí exponiendo esa
extraordinaria alabanza de nuestro Salvador:
"`Yo te alabo, oh Padre, Señor del cielo y de la tierra,
porque escondiste estas cosas de los sabios y entendidos,
y las has revelado a los niños.`" Ese directo favor de la amorosa bondad del Señor,
tuvo un gran impacto sobre mí;
me levanté de la silla y caí sobre mis rodillas para
recibir la sobreabundancia de su poder;
y tal fue el efecto,
que por medio de Su ayuda clamé desde mi alma unas cuántas palabras de súplica al Señor,
rogando una mayor manifestación de Su voluntad y Su preservación en ella.
Creo que ésta fue la oración más viva que jamás había hecho.

Después de haber permanecido un tiempo arrodillada, recordé que había leído el pasaje,
sin embargo deseaba leerlo de nuevo.
No tenía mi propia Biblia, ya que mi tía me la había quitado,
diciendo que no me serviría de nada,
como en efecto no me había servido de mucho hasta ese momento.
Sin embargo, al encontrar otra, busqué el pasaje,
y fijando mi mirada en él descubrí algo muy diferente en mí, y fui movida a decir:
"`Ciertamente el Cordero de Dios es digno de tomar el libro, y de abrir sus sellos.`"
A partir de ese momento supe que no estaba en mi
poder leer las Escrituras con el significado correcto,
sino solamente cuando se me concediera la llave de interpretación,
la cual empecé a recibir con frecuencia, para mi gran provecho y consuelo.
Así me familiaricé nuevamente con mi libro,
y valoré a ese buen compañero como nunca antes;
deseando ser guardada en el camino que había de seguir,
tener pan para comer y vestido para vestir, y poder volver en paz a la casa de mi Padre,
con la resolución de que el Señor sería mi Dios.

Mientras me rendía a Su santa voluntad,
le agradó al Todopoderoso mostrarme que no estaba bien que yo creyera de ese modo,
y que a la vez continuara sola,
sin reunirme con los que estaba convencida que eran creyentes del mismo Principio Divino.
Ni ahora creo que hubiera sido bueno o correcto que me quedara sola,
porque así como el Señor en Su sabiduría consideró
apropiado proveer compañeros idóneos para el cuerpo,
así, ciertamente,
en misericordia capacita a muchos de Sus fieles siervos
para que sean de mutuo provecho en un sentido espiritual.
Por lo tanto consideré que era adecuado que yo asistiera a las reuniones,
para conservar mi favor ante Él.

Mi tía no me lo impidió hasta que asistí unas cuantas veces más; y a además de eso,
tenía que lidiar con muchas otras cosas dentro de mí;
las lágrimas que derramé al entrar por la puerta y al presentarme delante del Ser Invisible,
ocasionaron muchas renuncias a mi propia voluntad.
Yo solía sentarme en el primer asiento que encontraba; pero me satisfacía tanto,
que lo que sembraba con lágrimas al llegar ahí, lo cosechaba con gozo al irme.

Al ir con deseos en mi alma por crecer, era a menudo muy favorecida,
y recordaba la recomendación que S. Radford me hizo:
"`Compra la verdad y no la vendas;`" así como de
estar convencida de la justicia del Todopoderoso,
y de que la destrucción del hombre proviene de sí mismo.
Creo que fue alrededor de ese tiempo, o un poco después,
que escuché a mi tío Joshua Toft,^
footnote:[Joshua Toft se unió a la Sociedad de Amigos
por convencimiento en los primeros años de su vida,
y por obediencia a las enseñanzas de la gracia Divina,
se convirtió desde joven en un buen ejemplo de religión y virtud.
En aquella época sus negocios le obligaban a estar mucho tiempo fuera
de casa y en compañía de personas que estaban poco familiarizadas con
el comportamiento cauteloso que su profesión religiosa requería;
de quienes, como consecuencia de su comportamiento, recibió malos tratos.
Pero su mente estaba tan revestida de paciencia, mansedumbre y amor,
que fue capaz de silenciar la ignorancia de los hombres insensatos; y a veces,
la enemistad contra él por su fidelidad, dio lugar al respeto y a la amistad.
Él empezó sus negocios modestamente,
pero la bendición de la Providencia Divina coronó sus honestos esfuerzos,
y cuando aún se encontraba en pleno vigor de la vida,
adquiría ingresos suficientes para subsistir.
Bajo estas circunstancias,
y con un negocio que progresaba y que le habría permitido acumular muchas riquezas,
con noble templanza dejó el negocio,
para dedicarse por completo al servicio de su gran Señor y Maestro.
Llegó a ser ministro a los treinta y dos años,
y trabajó fielmente como tal por muchos años en varias partes de Inglaterra e Irlanda.
Unos veinte años antes de su fallecimiento,
se vio muy incapacitado para viajar debido a un trastorno en su cabeza,
que en ocasiones afectaba su entendimiento,
y que lo privó de su vista durante más de catorce de los últimos
años de su vida.
{footnote-paragraph-split}
Después de esta prueba,
sus facultades mentales fueron restablecidas a su
fuerza inicial y continuaron lúcidas hasta su muerte.
Soportó grandes sufrimientos corporales, así como la pérdida de su vista,
con ejemplar paciencia, rendición y gozo,
expresando que creía que toda su aflicción le había sido impuesta en amor,
y que esperaba poder recibirla tal como había sido dispensada.
Un poco antes de su partida,
se sintió muy consolado a través de un aliento secreto albergado en estas palabras:
"`He estado contigo, estoy contigo y estaré contigo.`"
Partió tranquilamente de esta vida el 15 del octavo mes de 1769,
con más de ochenta años de edad, y fue enterrado en el cementerio de los Amigos en Leek.
(Del Testimonio de la Reunión Trimestral de Staffordshire).]
dar su testimonio de la verdad; y recuerdo que testificó como quien tiene autoridad,
animando a los Amigos a salir de Babilonia,
y exhortándolos a no participar con ella de sus pecados,
para que no participaran también de sus plagas.
Y aunque yo era muy joven en la verdad,
el Señor se agradó en iluminar mi entendimiento de tal manera,
que lo entendí espiritualmente,
y fui hecha partícipe de esa vida de donde proviene el poder.
Tampoco olvidaré las palabras de ánimo que recibí de otro Amigo,
que como la lluvia temprana y tardía, regó la plantación del Señor,
exponiendo la bienaventuranza con la que Él recompensa
a los que abandonan todo por Su nombre, etc.
Pues, aunque podía deleitarme en esas cosas,
vi que no debía edificar un tabernáculo aquí. Mis problemas no habían terminado del todo,
porque, aunque mi tía me dejaba ir con libertad unas cuantas veces,
se propuso complicar mi nuevo propósito,
exacerbando sus fuertes emociones y dando a lugar a las pasiones insensatas de otros.

La primera vez que me vio cuando me dirigía a la reunión, tenía un látigo,
y la siguiente vez una capucha negra y un delantal verde.
Pero procuraré ser lo más breve posible,
porque no quiero recordar las tontas molestias que se tomó para mortificarme.
Sin embargo, me siento obligada a reconocer con gratitud,
que fui preservada de todo el escarnio que recibí;
aunque para muchos fui objeto de entretenimiento y diversión. Algunos, sin embargo,
parecían compadecerse de mí; aunque no puedo decir lo mismo del resto,
pues tan solo conocía a tres o cuatro de ellos.
Entre esos, había uno que frecuentemente se mostraba preocupado por mi preservación,
y se ofrecía a ayudarme a utilizar la ley para obligar
a mi tía a comportarse mejor conmigo,
pero yo sentía un mayor deseo de ser preservada con pureza en relación con ella.

Otros de mis simpatizantes me aconsejaron que dejara el pueblo;
ofreciéndome una habitación en sus casas,
y la posibilidad de vender mi mercancía con ellos.
Debo reconocer que eso fue un gesto muy amable;
pero aunque me insistieron para que accediera, no me sentí inclinada a hacerlo,
pues pensaba que si me marchaba del pueblo se vería como si hubiera hecho algo malo;
y sabía que nadie podía decir de mí otra cosa peor que el hecho de que yo era Cuáquera.
Por lo tanto,
aunque de buena gana hubiera podido huir del bullicio que mi cambio había ocasionado,
aun así escogí encomendarme a esa Mano, que entonces creía que podía preservarme,
y sufrir el oprobio de ese momento, hasta que mi Dios dijera: "`¡Es suficiente!`";
pues no dudaba que esas cosas eran permitidas para probar mi fe.
Sin embargo, era tanta la amabilidad de ellos,
que me dispuse a pedir otro consejo al respecto;
y como Samuel Leay me había preguntado en otras ocasiones cómo me iba,
le expresé mi deseo y le pedí que me procurara una
oportunidad para hablar con uno de los Amigos Toft.
Él me preguntó con cuál de ellos.
Le dije que con cualquiera de los tres hermanos que me resultara más cómodo visitar,
sin que mi tío o tía lo supieran,
porque me angustiaba mucho más que abusaran de los demás,
que de mí. Al día siguiente me dijo que había hablado con Samuel Toft,
quien estaba dispuesto a darme la oportunidad de escucharme esa misma noche.

Según lo acordado, fui al anochecer como Nicodemo;
no tanto por vergüenza de hacerlo (a lo cual ya estaba acostumbrada),
sino por miedo a que mi tía se enterara de ello.
No sabía quién me iba a recibir bajo el nombre de Samuel;
pero al tocar la puerta me dejó entrar.
Después de saludarlo, me senté;
y comencé la conversación diciéndole que suponía
que él no era ajeno al tumulto del pueblo,
y a la indignación que mis tíos sentían con respecto
a mí. Le di a entender que no podía evitarlo,
pero, que a pesar de ello, me encontraba dispuesta a unirme a la Sociedad.
Más adelante le dije de la amable oferta que me habían hecho,
pero que al dudar en mi mente sobre qué sería lo mejor,
había sentido el deseo de pedir consejo.
Me dijo que si me marchaba, sería la forma más fácil de librarme de esos problemas;
y luego me preguntó si tenía esperanzas de que mis parientes cambiaran de parecer.
Le dije que no; que más bien temía que se volvieran peor,
porque habían dicho que no se calmarían mientras siguiera siendo Cuáquera.
Entonces me dijo: "`Ese es un buen punto de referencia para darte un consejo,
porque quién sabe lo que tus parientes podrían llegar a hacer en su ira,
o cómo lo llegarías a soportar;
quizás la mejor forma de estar a salvo de ellos sea
aceptando las propuestas de tus amigos.`"

Esto, sin embargo, no era lo que yo esperaba, ni lo que yo deseaba;
y para acercarlo un poco a mi perspectiva, le dije: "`¿Crees, señor,
que hay lugar para creer que sería presuntuoso de mi parte,
si me quedara y recibiera alguna afrenta de parte de ellos?`"
Él dijo que no lo creía, siempre y cuando yo no les diera una razón de hacerlo; y añadió:
"`Jovencita, ¿qué crees que es lo mejor para ti?`"
Le respondí: "`Yo no me pondría intencionalmente en peligro,
ni actuaría a propósito para provocarlos;
pero no veo cómo en este momento podría escapar de su enojo y abandonar el pueblo,
sin ocasionarme una secreta intranquilidad.`"
A lo cual respondió: "`Sin duda,
debemos prestarle atención a tales sentimientos de intranquilidad,
porque podríamos salir de un problema para meternos en otro, y quizás uno peor.`"
Luego me preguntó cómo creía yo que podría soportar la prueba,
diciendo que yo ya había experimentado algo de esa clase de pruebas.
Le respondí: "`Sí, es cierto; y he encontrado a la Verdad de mi lado tan fuertemente,
que hasta ahora he sido sostenida por ella a través de las pruebas; y ahora no dudo,
que si perdiera la vida a causa de la ira de mis parientes,
mi alma seguiría estando feliz.`"
Él me hizo saber que si ese era mi parecer y mi decisión, no podía decirme nada más que,
"`sigue adelante y prospera.`"

Deseándole lo mejor de la noche,
regresé anhelando permanecer firme en lo que consideraba mi deber; pero estando en casa,
no podía dejar de pensar en la poca confianza que le había dado a ese Amigo,
y en especial por la extraña apariencia que tenía,
tratándose de una Cuáquera;
porque aparte de mi forma de hablar, iba completamente arreglada.
Llevaba puesta mi gargantilla, anillos en mis dedos y aretes en mis orejas.
Mi vestimenta era de luto, de crespón blanco y negro que llevaba por mi amada hermana,
y por esa razón mi lino carecía de encajes;
pero en ese entonces no me preocupaba por mi apariencia externa,
mi obra yacía más en el interior.
Pero parece que mi amigo no se fijó tanto en mi apariencia
como para ignorar las intenciones de mi corazón;
porque Samuel Leay me dijo la siguiente vez que me vio,
que S. Toft había dicho que estaba convencido que dentro
de mí había algo que me haría desistir de los halagos;
y no pasó mucho tiempo antes de que yo me diera cuenta de que era mi deber hacerlo.
Pero ahora debo mencionar una posible razón por la que no se me
permitió darle a mi amigo una mayor certeza de mis intenciones;
y que además puede reflejar lo ciega que estaba en cuanto a mi propio estado,
y cuánta necesidad tenía de implorarle a la luz Divina que dirigiera mi camino;
porque aunque yo creía que estaba bastante segura en cuanto a mi propósito,
enseguida descubrí, por experiencia, lo débil que era.

Recibí una carta de mi querido hermano (que había tenido
la amabilidad de visitarnos cuando murió mi hermana),
diciéndome que se había enterado por mi tío,
del lamentable asunto que había entre nosotros;
explicándome el comportamiento fanático y extraño
de aquellos con los que estaba a punto de unirme,
el gran error en que se encontraban con respecto a las doctrinas de Cristo,
y extendiéndome a la vez una amable invitación para que me fuera con él,
prometiendo cuidar de mí y de mis posesiones.
Mencionó con mucho cariño,
que tenía una oportunidad de ubicarme con una pariente cercana de su esposa,
que era sombrerera en la ciudad, si me interesaba ese negocio;
y concluyó con mucho amor fraternal, y deseándome todo lo mejor.

Esto alcanzó profundamente el cariño natural que le tenía,
que de no haber sido favorecida por el Altísimo para
ver la trampa que mi enemigo me había tendido,
hubiera aceptado sin duda la oferta de mi único hermano.
La consideración de su amor reflejada en su propuesta,
y la aflicción que le había provocado a mis parientes cercanos y queridos,
hizo que yo volviera a considerar la razón de mis problemas,
y examinara la causa de ellos.
Bajo este profundo análisis,
muchas súplicas secretas fueron dirigidas al Señor pidiéndole preservación y ayuda,
a fin de que el enemigo fuera derrotado en todas sus estratagemas.
Así fui atacada en mi lado más débil;
pues este amable trato de parte de mi hermano y las últimas tres visitas de mi tío,
me perturbaron más que todos sus maltratos.
Sin embargo, me tocó responder a la carta, y lo hice tan cuidadosamente,
según esa sabiduría que mi Padre Celestial se complació en darme,
que no volví escuchar de mi hermano sobre aquel asunto,
sino que todas la demás veces que me escribió después de eso,
lo hizo con gran amor y respeto.

Gracias a las misericordias del inexpresable amor de mi Dios,
había superado muchas dificultades y dudas en mi mente; sin embargo,
me quedaban varias pruebas aún que atravesar, como se mostrará a continuación.

El cambio en mi forma de hablar ocurrió de la siguiente manera; una mañana,
mientras estaba acostada en la cama, se apoderó de mi mente un ejercicio difícil,
y mientras esperé conocer la causa, me fue mostrado que debía usar el lenguaje simple.

Ya había considerado este asunto anteriormente,
y apenas tuve tiempo de reconsiderarlo y probar que era verdad,
cuando mi tía llamó a la puerta.
Yo conocía sus pisadas, que me hacían temblar, por lo tanto, no me apresuré en vestirme;
pero como sabía que debía someterme, me dirigí a la puerta y le dije: "`¿Quién es?
¿Qué es lo que tú quieres?
Ella me dijo: "`Déjame entrar y te diré.`" Yo no cuestioné en lo más mínimo lo dicho;
y en seguida me lo hizo saber,
con muchas amenazas de lo que ella sería capaz de hacerme si yo la volvía a "`tutear.`"
No podía evitar pensar que se me había pedido algo muy difícil, es decir,
exigir que comenzara este cambio de lenguaje con mi tía; sin embargo,
debido a la satisfacción que experimentaba en mi mente, encontré aliento en la verdad,
y a partir de ese momento no me retraje más de esa parte de mi testimonio,
excepto con mi tía, a quien de ninguna manera me agradaba afligir, y por ende,
esquivaba el lenguaje simple tanto como me era posible; y en lugar de usar el plural,
interrumpía muchas veces el hilo de nuestra conversación,
hasta que pude ver claramente que no iba a ser posible, y que debía quebrantar mi paz,
o exponerme a la furia de mi tía.

Y no tardé en experimentarlo; pues al usar la palabra tú con ella, se enfureció tanto,
que tomó una pala de chimenea que estaba cerca de ella,
y me atacó. Como mi hermana estaba en la pequeña habitación la agarró, o de lo contrario,
mi tía habría llevado a cabo su amenaza,
pues la habitación o armario detrás de la tienda era tan estrecho,
que no tenía espacio ni para dar un paso atrás. Así fui preservada una vez más;
pero tenía razones para temer que yo sería la causa de llevar deshonra a mi tía,
como ella solía decirme, pues a menudo expresaba que no era más pecado matarme a mí,
que a un perro.

Supe que ella se había enterado del consejo que había recibido de abandonar el pueblo;
y creo que sufrí mucho por ese gesto de amabilidad de parte de mis amigos.
Las expectativas de mi tía parecían ser ahora,
o que ellos me convencerían de que saliera, o que ella me echaría del pueblo,
porque dijo que si me convertía en Cuáquera, no lo sería ante sus ojos.
Entonces la amable oferta me fue extendida de nuevo;
P+++.+++ Heller me envió una invitación para que fuera a Whitehaugh por un trimestre,
hasta que mi tía se calmara.
Ciertamente, fue una generosa invitación de alguien a quien nunca le había hablado.
Y con respecto a mi escuela o mi trabajo, fácilmente habría podido dejar la ciudad;
pues el comportamiento de mi tía había asustado tanto a mis alumnos,
que sus padres consideraron adecuado mantenerlos en casa;
y si no hubiera sido por el hecho de que algunos
querían ver a alguien a quien llamaban Cuáquera,
difícilmente hubiera vendido tantas baratijas como lo hice;
porque había cierta curiosidad por verme.

Yo habría aceptado de buena gana la amable invitación de mis amigos,
pues entonces era objeto de menosprecio y burla;
pero al fijar mis ojos en el Capitán de mi salvación,
encontré que no sentía la libertad de irme, y entonces, tras reconocer su amabilidad,
dejé pasar la oportunidad.

Otra muestra de las pasiones desenfrenadas de mi tía ocurrió poco después,
cuando estábamos sentadas en el cuartito (como solíamos hacer con
frecuencia) y nos acercábamos a la mitad de la noche;
entonces,
en el curso de nuestra conversación me obligó a usar
ese lenguaje que ella no soportaba escuchar,
y cogiendo un candelabro de bronce que estaba entre nosotras,
me lo tiró con tal fuerza que fue a dar contra la pared.
Yo apenas tuve tiempo para reaccionar, y al agacharme esquivé su golpe.
De esa manera me preservó nuevamente el Dios de David, por amor al vástago de Isaí,
que en ese entonces comenzaba a arrojar renuevos en mi corazón;
y aunque mi cuerpo físico peligraba,
aun así fui misericordiosamente preservada con certeza en mi alma,
y con la firme creencia de estar en el camino que era mi deber.
Asimismo fui favorecida, con la esperanza como un ancla, con esta convicción,
de que si al Señor le agradaba permitir la muerte de la parte mortal,
se complacería en hacer que Su misericordia se apoderara de mi alma inmortal,
y moriría como una mártir de mi fe en Cristo.
No obstante, un temor por mi tía prevalecía sobre mí;
y aunque había encubierto su comportamiento hacia mí lo más que había podido,
aun así no me atreví a ocultarlo más, por miedo a ser culpada de las consecuencias.
Por lo tanto,
le pedí a mi hermana que le hiciera saber a mi tío
de ese acto tan violento y de mis temores.
Él me mandó a decir que cualquier trato que yo recibiera era lo que merecía;
y que en cuanto a mi tía, le era imposible hacer que se quedara en casa.

El dolor que atravesé por el temor a que mi tía enloqueciera fue muy grande,
y fueron frecuentes las veces en las que mi alma y mi cuerpo se postraron ante el Todopoderoso,
suplicando fervientemente que nos preservara a ambas; a ella en sus facultades mentales,
y a mí en el camino de mi deber hacia Él,
y en una conducta recta hacia mis tíos. Creo que en ese entonces,
mi tío sentía más compasión por mí de la que me dejaba ver;
habló con mi tía y no le permitió volver a visitarme a horas tan inoportunas;
porque en muchas ocasiones anteriores,
ella había pasado la mayor parte de la noche a solas conmigo,
y lo que recibía de ella sólo el Todopoderoso lo sabe, y en efecto,
me lo compensó más tarde con mi reconciliación con ella.
A partir de ahí terminaron sus visitas nocturnas,
pero habían sido tan frecuentes y prolongadas,
que me había acostumbrado a pasar las noches en la pequeña habitación,
donde solía mantener un pequeño fuego en la chimenea.
Pasaba mucho tiempo sentada allí, y cuando se acercaba la hora de dormir,
si mi tía no estaba,
apagaba mi candela y me sentaba tan quieta como podía
para que no sospechara que estaba trasnochando.

Durante ese tiempo no tenía a nadie con quien conversar, o quien me animara,
permanecía completamente sola; sin embargo, las directas visitaciones del Divino favor,
en ocasiones confirmaban misericordiosamente mi fe,
y cuando estaba a punto de sentirme abrumada, el Señor con Su misericordiosa compasión,
dirigía mi mente hacia algunos pasajes de las Escrituras, para mi gran consuelo,
y pocas veces las leí o las contemplé sin derramar lágrimas.

Sin embargo, no tardé en perder la perspectiva y el efecto de esos favores,
y como una viajera alejada del refugio de su felicidad por vientos adversos,
caía en confusión de pensamientos debido a mi dolor; y con frecuencia,
era abatida bajo las severas insinuaciones del enemigo, hasta las dos, tres, cuatro,
o cinco de la mañana; y a veces, tan pronto me acostaba en la cama, mi tía me llamaba.
Es difícil de creer lo poco que dormía; pero sin duda,
sentía compasión por mis tíos debido la aflicción que les causaba.
La comida era tan insignificante para mí como el sueño, comprobando de este modo,
lo poco que se necesita para subsistir.
Mis tiempos de comida eran inconstantes; mi único alimento por meses fue,
un poco de pan y queso con un poco de agua o leche,
o pan y mantequilla con una taza de té; tampoco deseaba comer nada más,
hasta que la necesidad me obligó a cambiar mi rutina.

Aunque mi tía se restringía un poco en su trato hacia mí,
me dijo que continuaría haciéndome sufrir,
afirmando que nadie se tenía que meter con lo que ella me hacía. Un día de mercado,
me siguió detrás del mostrador y me mantuvo allí por unas horas,
diciendo que ese día escucharía mi lenguaje; y aunque le pedí que me dejara ir,
no lo hizo;
ni yo me atreví a apartarla de mí. Ciertamente me encontraba bajo un ejercicio,
y deseaba realizar mi deber ante los ojos del Ser Divino;
aunque temiendo sufrir por ello.
Cuando alguien llegaba a la tienda le decía que yo era la recién convertida Cuáquera;
llenando de asombro a los extraños,
y puedo decir que me avergoncé tanto por ella como por mí misma.
Siempre que me exponía de esa manera, me agarraba el brazo izquierdo,
que era el que estaba a la par de ella, y cada vez que yo usaba el lenguaje sencillo,
me pellizcaba muy fuerte;
y lo hacía con tanta frecuencia que me resultaba muy difícil soportarlos.
Sin embargo,
no encontré la forma de evitar sus abusos sin tratarla como jamás lo había hecho,
y acarrear de esa manera culpa sobre mí; por lo tanto,
me esforcé por aguantar un poco más,
y desde entonces me pregunto cómo fui capaz de soportarlo sin quejarme.
En efecto, ella me había acostumbrado a sufrir;
y con frecuencia decía que los Cuáqueros me habían enseñado,
y que si ella me golpeaba una mejilla, yo debía ponerle la otra.
Ella me afligió tanto esa vez, que le rogué que se detuviera en varias ocasiones;
pero no esperaba que fuera a considerar mi petición. Sin embargo,
como mi brazo y mi mano estaban visiblemente hinchados,
yo esperaba que el aspecto del brazo y de la mano abogaran por mí, y de tanto mirarlos,
logré que ella se percatara; entonces me dijo burlonamente:
"`Dudo que haya lastimado tu brazo;`" y poco después se marchó. Cuando se fue,
intenté desabotonar mi manga, pero como mi brazo estaba muy hinchado,
me fue imposible hacerlo.

Como la hija del doctor Gravesnor sabía que mi tía había estado mucho tiempo conmigo,
cuando la vio salir de la tienda, entró, y me ayudó a desabotonar mi manga.
Cuando me soltó el puño, mi mano y mi brazo se hincharon a tal punto,
que viendo el estado en que estaban, fue a buscar a su padre,
y antes de que llegara el doctor, apenas podía cerrar mi mano.
Cuando vio mi brazo, dijo que estaba muy magullado;
parecía tener el tamaño del ancho de la palma de la mano,
y estaba como una gelatina y extremadamente negro hasta el hombro.
El doctor se mostró sorprendido, y dijo que temía una necrosis;
luego se fue a su casa y regresó rápidamente con una medicina.
Él siempre me había mostrado mucho respeto;
y sus hijas fueron mis alumnas hasta que mi tía decidió ponerle fin a la escuela.
Creo que fue tanto por su respeto, como por su preocupación,
que después de vendarme el brazo,
se tomó la libertad de reprenderme y reprocharme por haber permitido tan tonta e ingenuamente,
ser tratada de esa forma;
afirmando que mi caso era peligroso y que podía perder mi brazo, o incluso la vida;
sin embargo, añadió que haría todo lo que estaba a su alcance para evitarlo.
Yo le dije que le agradecía su bondad y consejo,
y que en ese entonces estaba más dispuesta a renunciar a mi vida que a mi brazo;
sin embargo, yo luchaba en lo profundo de mi mente para sujetarme a la voluntad de Dios;
y viendo el doctor caer mis lágrimas dijo: "`No,
ciertamente tienes bastante que soportar, sin que te regañen`". Y así lo experimenté,
porque aparte de mi ejercicio interno, su intervención era muy dolorosa.
Dijo varias veces que temía por el hueso,
y que aquello era una crueldad de la que nadie en su sano juicio podría ser acusado.
Permaneció conmigo por bastante tiempo, cambiando a menudo los vendajes,
lo que reavivaba mi dolor.

Mis dedos estaban rígidos, hinchados e inútiles,
por lo que me era imposible moverlos o cerrar mi mano.
El doctor me preguntó si había alguien que pudiera cuidarme,
ya que no vivía en la casa de mi tío;
y añadió que no iba a poder estar sin una persona que me ayudara,
y le pidió a su hija que no me dejara sola hasta que encontrara a alguien.
Cuando se fue, mandó a llamar de una vez a mi tío,
y le dijo que mi tía me había tratado de una manera anticristiana;
agregando que ella merecía más estar atada que andar suelta,
y que él no debía permitirle acercarse a mí. Mi tío le prometió que ella no lo haría;
sin embargo, esto no hizo que se compadeciera de mí y fuera a verme,
que era lo que yo más deseaba.

Transcurrió un mes hasta que fui capaz de volver el brazo hacia atrás para poder vestirme.
Mis tíos enviaron a mi hermana a la escuela en Manchester por miedo, como sospechaba yo,
a que se le pegara la infección de una Cuáquera; no obstante,
yo no lamenté mucho la pérdida de su compañía,
pues descubrí que había actuado deslealmente entre nosotras.
Mientras me encontraba en esa condición, pocos llegaron a verme;
pero oí que muchos estaban disgustados con mi tía. Dentro de esos pocos que llegaron,
estaba la que entonces era mi tía, S. Whitehead; y su visita fue muy agradable,
aunque apenas la conocía. Me animó mucho y me invitó
a visitarla una vez que se restableciera mi salud;
lo cual habría podido hacer de buena gana,
pero consideré apropiado postergar la visita por un tiempo,
pues temía que mi tía se enterara de ello, ya que no perdonaba a nadie,
cuando se enteraba que se habían dirigido a mí de manera amigable.

Durante esa época, S. Taylor vivía con John Winter, en Stafford;
y como sabía que mis tíos sentían una aversión sin fundamento hacia esa familia,
les pedí que no me visitaran tan a menudo.
Ellos comprendieron mis motivos,
pasaron por alto la libertad que me tomé con respecto a ellos, y cuando yo los visitaba,
se comportaban cariñosos y desinteresados.

Aquí no debo olvidar, y espero nunca hacerlo, al mejor de los visitantes,
al Consolador invisible; quien,
en gran medida aliviaba mis aflicciones y consolaba mi espíritu,
bajo la creencia de que perseveraba en el camino de mi deber.

Así, gracias al ánimo que sentí internamente, me dispuse,
tan pronto como fuera apropiado,
a hacer un esfuerzo por asistir a las reuniones de nuevo.
Y en cuanto me recuperé hasta el punto de vestirme sola, pensé,
que al estar en un estado tan débil,
sería mejor para mí si me alojaba con una familia
para garantizar el sustento que mi constitución requería;
la cual nunca había sido demasiado fuerte,
y en ese entonces estaba muy debilitada por el exceso de aflicciones,
y por mi diferente forma de vivir.
Como había una puerta en mi apartamento que daba a la otra parte de la casa,
pensé que era conveniente alojarme con Thomas Turnock, quien vivía allí;
y me sentí muy satisfecha de haberlo hecho.

Debido al distanciamiento de mi tía durante el último mes,
tenía cierta esperanza de que no volvería a impedir que fuera a las reuniones; pero,
ya fuera por casualidad o por información, no lo sé,
mi esperanza rápidamente se vio frustrada.
Porque un día, cuando iba por la esquina, cerca de la casa de mi tío,
la vi acercarse a mí. Las palabras del doctor y la
condición de mi brazo rápidamente vinieron a mi mente;
y pensé que si permitía que me lastimara de nuevo, las consecuencias serían muy graves.
Como estaba en libertad,
me pareció mejor seguir estándolo y arriesgarme a continuar en dirección a la reunión;
sin embargo, me sentí tan confundida, que después de haber caminado unos cuantos metros,
flaqueé en mi propósito,
y mi tía me alcanzó antes de haber llegado a la mitad del
camino rumbo a la reunión. Entonces me di cuenta de mi error,
y de que hubiera sido mejor dejar que mi tía me alcanzara antes;
pues el lugar donde estábamos se veía peligroso,
y la falta de espacio para intentar sacudirme y empujarme,
me hizo temer que me arrojara de cabeza por el precipicio.
Como era más o menos la hora en que los Amigos se reunían, eso la molestó aún más;
pues tenía razones para creer que ella no soportaba ver a un Amigo por mi causa.
No dejó de amenazarme con hacerme daño en el brazo, ni dejó de sacudirme por él;
pero como tenía unas cuantas capas de franela, fui preservada.
Mi tía no olvidó mi esfuerzo por caminar más rápido que ella;
pues lo mencionó varias veces después,
dando a entender que Dios había estado por encima de mi espíritu perverso.
Así me retuvo, con muchas amonestaciones y exhortaciones, como ella las llamaba,
hasta que consideró que el tiempo de la reunión había terminado, y luego me dejó ir.

Como ya me encontraba en libertad, me dirigí a la reunión, y como no había terminado,
entré, para darle a entender a mi tía que mi intención seguía en pie.
Eso sin duda reanudó nuestros encuentros, pues no tardó en repetir sus visitas,
aunque no lo hacía a las horas inoportunas de antes.

Muchas veces he reflexionado con seriedad, sobre cómo me fue en ese tiempo de estrechez,
y puedo reconocer que mi compostura se debió a un
poder Divino que colocó mi mente en Dios,
y mantuvo sujetas esas pasiones naturales, que de otro modo,
habrían sobrepasado sus límites.
¡Oh, la serenidad y tranquilidad que gobernaron mi corazón en esos momentos de prueba,
cuando la inocencia prevalecía sobre la confusión! Y encontré,
que por someterme a esas lecciones de negación al yo, crecí en paciencia y rendición;
anhelando el favor del Señor y la manifestación de Su voluntad,
pues Él llevó mi corazón a un grado de sumisión tan favorable,
que estaba dispuesta a sufrir, o a ser llamada cualquier cosa,
antes que perder el disfrute de aquello que entonces poseía en una pequeña medida.

Fue durante ese tiempo que experimenté un éxtasis de gozo,
al rendir libremente mi nombre al que una vez consideré que era el más despreciable.
En una ocasión, llegó a mi tienda un sastre londinense con el que solía negociar,
y se dirigió a mí en la forma acostumbrada;
y como yo no respondí a su cumplido de la forma tradicional, me miró fijamente y me dijo:
"`¿Eres Cuáquera?`"
Esa pregunta me llegó directo al corazón; y con solemnidad le respondí:
"`Sí;`" e inmediatamente un brote de alegría se apoderó de mi corazón,
junto con este anhelo: "`No sólo Cuáquera Señor;
sino concédeme ser una '`verdadera israelita`'`" (Juan 1:47).

Mis buenos deseos fueron confirmados a partir de ese momento,
y mi anhelo de ser israelita se convirtió en mi ejercicio.
Pero aquí no puedo dejar de señalar, cuán tonta me veía ante mis propios ojos;
pues parecía que un gran cambio se estaba produciendo en
mí. No podía entonces elogiar con la misma facilidad,
y consideré que era mejor alejarme de todas las palabras superfluas
y de las conversaciones desenfrenadas que antes me permitía hacer.
El camino de mi deber me hizo objeto de tantas palabras airadas y preguntas difíciles,
que mi naturaleza estaba desconcertada,
hasta el punto de perder la esperanza de recuperarme; sin embargo,
a menudo contemplaba el beneficio que había recibido Zaqueo de aquel llamamiento celestial:
"`Date prisa, desciende.`"
Y cuán dispuesta estaba a que mi situación fuera como la de él;
creyendo que había algo en ese llamado que aludía a las glorias de la eternidad,
que ahora resplandecían con mayor brillo ante mis ojos que
todos los objetos brillantes de esta vida transitoria.
Sin duda, el tiempo se deslizaría dulcemente,
si contara todas aquellas refrescantes perspectivas
que me acompañaban en mis momentos de dolor;
pero la continuación de mi historia me llama a negar mi inclinación.

Por esa época John Toft me dijo que me visitaría,
pero aquella noche me enfrenté con un gran disgusto; pues mi tía llegó muy enfadada,
y colmándome de insultos, levantó una turba alrededor de la puerta,
haciendo que él pasara de largo.
Cuando mi tía decidió tranquilizarse,
cerró la puerta y se sentó. Traté de alejar de mi
mente los pensamientos de su desagradable conducta;
sin embargo,
no podía evitar sentir dolor por haber perdido la oportunidad de reunirme con el Amigo,
pues yo anhelaba verlo,
ya que él había sido un instrumento de beneficio
para mí. Mientras consideraba estas cosas,
llegó un mensajero y me dijo, que aunque mi tía estaba allí (si yo consideraba oportuno),
él llegaría a visitarme.
Dudé un poco, preguntándome qué sería lo mejor,
pues sabía que debido a la inestabilidad emocional de mi tía, ella no me perdonaría,
ni le importaría decir lo que fuera al calor de sus emociones; sin embargo,
tenía la esperanza (ya que él deseaba visitarme),
de que él pasaría por alto todo lo que le pudiera suceder,
y que vería más allá de las mentiras con las que ella pudiera arremeter contra mí.

Llegando a esa conclusión, le pedí que llegara, y como mi tía estaba allí,
me dijo que se quedaría para ver a ese Amigo.
Apenas tocó la puerta lo dejé entrar con cierto grado de temor,
y escuché el saludo que mi tía le dio: "`¡Engañador! ¡Anticristo!
Has seducido a esta tonta infeliz.`"
Si ella hubiera sabido todo lo que mi corazón podía decirle,
habría pensado muy diferente;
porque la llegada del Amigo me hizo muy consciente de ese
poder por el cual había sido atraída a la verdad.

Él se esforzó por demostrarle lo descabellada que era su acusación,
al asegurarle que nunca antes había tenido una conversación conmigo,
ni me había visitado en el pasado.
Ella le respondió: "`Si no lo has hecho tú,
tus hermanos sí;`" y continuó con vehemencia contra los Cuáqueros.
Aun así,
él intentó llamar su atención al recordarle que la mamá de él y ella (que eran vecinas),
solían conocerse.
Ella le dio a entender que eso era verdad,
y que si acaso había un Cuáquero bueno en el mundo, su madre era una.

Caminó de un lado a otro entre la tienda y el dormitorio,
acusándome de muchas cosas graves, las cuales había aprendido a soportar en silencio,
hasta que tocó mi modestia, y le dijo al Amigo sobre la libertad, que según ella,
yo me tomaba con los muchachos; entonces le pedí que se atuviera a la verdad.
Ella dijo que si yo decía una palabra más, golpearía mi cabeza contra la pared; lo cual,
yo sabía muy bien que una o dos palabras más, la habrían llevado a hacerlo.
Cuando él le preguntó: "`¿Desde cuándo es tan mala ella?`"
Ella le respondió: "`Desde que la engañaron,
porque estaba bastante bien antes de que la hechizaran.`"

Así continuó, mientras tuvo las fuerzas para hacerlo, según creo; porque al salir dijo:
"`Me iré, pero regresaré pronto.`"
Mas no regresó hasta el siguiente día,
donde me atacó con golpes y me culpó de haber mandado
a llamar al Amigo con el fin de afligirla.
Ella se había dejado llevar tanto por sus pasiones,
que el Amigo me expresó que no podía pensar otra cosa,
sino que ella se encontraba fuera de sí misma;
y que no concebía cómo yo podía mantenerme en pie,
si no fuera porque tenía a la Verdad como mi cimiento.
Le contesté que no tenía otra intención de estar entre los Amigos,
más que procurar la verdad y la paz de Dios en mi alma;
y que aún albergaba la esperanza de que iba a ser preservada.
Él me habló del vacío de una profesión estéril,
y me aconsejó esperar en Dios en lo secreto de mi corazón,
depender de Su sabiduría y confiar en Su poder,
expresando a la vez el deseo de que yo fuera preservada.
Luego añadió que habría ido a verme antes,
pero que se había visto obligado a seguir el consejo del apóstol,
de "`no imponer con ligereza las manos a ninguno;`"
y después de invitarme amablemente a su casa,
se fue.
Yo le devolví la visita en el plazo de un mes.

Después de que se marchó, reflexioné en lo que había pasado,
y me sentí agradecida con el Gran Preparador de todas las cosas.
Pensé que había algo extraordinario en el hecho de que mi tía nos hubiera dejado solos,
porque nunca antes me había dejado con una persona;
y estaba contenta de haber tenido la oportunidad de haber recibido tal instrucción,
como jamás había recibido en una conversación. Tampoco
pude dejar de admirar el prudente cuidado del Amigo,
al considerar el consejo del apóstol,
el cual yo había pensado que sólo se refería a la imposición de las manos del obispo,
en el momento de la admisión del joven pupilo a las órdenes sagradas,
y a la confirmación de la juventud.
Pero entonces supe por experiencia,
que yo había sufrido por la falta de esta prudencia en algunos otros casos.
Por ejemplo, mencionaré una de las reuniones más incómodas a las que he asistido,
que se originó por el excesivo cuidado de una Amiga,
que había insistido bastante para que yo me sentara más adelante de donde solía hacerlo.
Le dije que el lugar más privilegiado de la reunión sería
tan despreciado por mi tía como el lugar más bajo,
en caso de que se dispusiera a causar disturbios allí; sin embargo,
ante la gran insistencia, y al encontrarme dispuesta a mostrar respeto a su consejo,
me dejé persuadir, y me senté una o dos filas más adelante.
Pero cuando la Amiga llegó y vio que no había seguido completamente su consejo,
me tomó del brazo,
y aunque le manifesté mi deseo de permanecer sentada
(en la medida que los modales me lo permitieron),
me obligó a levantarme,
y pese a que le mostré mi deseo de sentarme en el primer o segundo asiento que viera,
no me dejó tranquila hasta que me hubo colocado en un asiento a su lado.

Entonces, ¡oh!, el desconcierto que había en mi mente; porque ciertamente,
si mi tía misma hubiera estado allí,
no habría podido perturbar mis pensamientos ni la mitad;
pues aunque en ese tiempo deseaba acercarme a los Amigos en espíritu durante las reuniones,
aun así,
iba muy en contra de mi voluntad sentarme tan cerca del
lugar que mi tía solía decirme que debía ser mi asiento;^
footnote:[Es decir, el lugar donde solían sentarse los ministros itinerantes.]
alegando que todos los prosélitos debían convertirse en predicadores,
y declararles a los hermanos las abominaciones de los impíos.
Con frecuencia se burlaba de mí con tales cosas,
sabiendo muy bien que sentía una gran aversión a la idea de que las mujeres predicaran.

Ahí me senté, en un estado intranquilo, deseando salir en muchas ocasiones; sin embargo,
el aprecio que sentía por la Amiga hizo que me quedara.
No obstante, me alegré cuando terminó la reunión, y al finalizar me dio su mano,
y yo le correspondí con la mía, como muestra de haberla perdonado por su precipitado,
aunque amoroso acto; pero no sin decirle, una vez en casa,
la angustia que me había causado, y le rogué que no lo volviera hacer.

¿Debo decir aquí que algo bueno salió de lo malo?
No exactamente, sino que de lo amargo salió algo dulce;
pues debido a la libertad que se tomó esa Amiga en darme su mano,
varios de los que estaban en la reunión hicieron lo mismo,
y aunque esto no probó ser un momento de confirmación de mi fe,
sino más bien todo lo contrario, aun así, pareció ser una señal de unión,
ya que nadie lo había hecho antes conmigo, y estaba complacida.

Por un tiempo perdí el profundo efecto que me había causado el comentario del Amigo,
de que mi tía había perdido la razón;
pero después pensé que si por lo poco que él había visto, tenía ese tipo de opiniones,
cuánto más tenía que temer yo, que la había visto tantas veces mucho peor.
Sin embargo, qué podía hacer, o qué más tenía que hacer;
no podía renunciar a mi salvación con tal de apaciguar a mi tía.
Estas consideraciones llenaron de angustia mi semblante,
lo que animó a mi tía a decir que podía ver en mi rostro a la mismísima Cuáquera.

Me parecía casi imposible que yo fuera capaz de experimentar
un dolor semejante al que sentía entonces;
y mi tía, ya fuera por información, o a partir de sus propias conclusiones,
se puso al tanto de ello; y me hacía creer, por medio de muchos actos frenéticos,
que ella realmente era como yo imaginaba.
Mi alma entonces huyó al Todopoderoso en busca de refugio,
y soporté el comportamiento frenético de mi tía con
más cautela y tranquilidad de lo que ella esperaba.
Entonces se puso frente a mí y me dijo: "`¡Estoy loca! ¡Tú,
tú me has vuelto loca! ¡Y estoy loca!`"
Me sorprendí al escucharla decir eso, y pensé que me quedaba un poco de esperanza,
pues era lo suficientemente cuerda como para hablarme
de aquello que ella sabía que yo tanto temía.

Al verme tan tranquila al respecto, ella desistió de ese plan, y en seguida,
como quien desfallece en sus esperanzas de victoria, dejó de molestarme en la calle.
Sin embargo, queriendo entorpecer mi deseo de ir a la reunión,
llegaba a mi habitación antes de la hora señalada;
diciéndome que íbamos a tener una reunión en silencio,
y de buena gana hubiera querido que lo hiciera, pero parecía algo imposible de su parte.

Cuando me percaté que por medio de esa práctica,
ella intentaba mantenerme en casa para evitar que yo fuera,
me dispuse a salir mucho antes de lo usual; y ella, por su parte,
llegaba mucho más temprano, hasta que entendió,
que a menos que se levantara más temprano por la mañana,
mis resoluciones superarían a las suyas.

Por ese motivo me vi obligada a andar por los campos; pero mi esfuerzo no fue en vano,
porque finalmente mi tía me permitió andar libremente,
y participé de muchas preciosas reuniones.
Como no confiaba en absoluto en una religión de tradición,
cuando estaba ahí mi más ferviente anhelo era buscar al Señor;
y Él fue hallado por mi alma, para mi inexpresable consuelo.

Con respecto a las reuniones en silencio,
mis ejercicios espirituales en casa me habían enseñado
la manera de beneficiarme de ellas;
inclinando mi corazón a permanecer en temor y reverencia,
y a vigilar contra los pensamientos bulliciosos e innecesarios,
en lugar de ocuparme (como solía hacerlo) en las
llamativas manifestaciones de la adoración de labios.
Pero no quiero que parezca que no encontraba ninguna dificultad durante mis ejercicios;
porque ciertamente a menudo me embargaba una nube
de pensamientos naturales que me oprimían tan intensamente,
que me veía obligada a implorar por Divino auxilio, y a exhalar este clamor: "`¡Señor,
si no guardas la ciudad, en vano vela la guardia!`"
A pesar de haberme librado de las persecuciones de mi tía,
descubrí que sólo había cambiado de escenario,
y que la sutileza de la serpiente me resultaba más
peligrosa de lo que había sido la furia del león.

No pude dejar de reconocer con gratitud, y con anhelo de responder a mi deber,
la libertad que tenía para asistir a las reuniones,
de las que hasta entonces había sido muy restringida,
y la misericordia del Señor al subyugar aquellos
espíritus que impedían la serenidad de mi alma.
Pero yo era todavía muy inexperta en las artimañas del enemigo y engañador de los hombres,
y necesitaba la ayuda de algún amigo íntimo y prudente,
cuyo consejo pudiera ayudarme a ponerle límites correctos a mi celo.
El sutil adversario, aprovechándose de mi seriedad,
astutamente enredó un hilo suyo en esa obra que yo
me esforzaba por rendir con aceptación ante mi Dios.
Hasta ese momento,
me había dedicado a buscar un incremento y a afianzarme en el conocimiento de la verdad,
y a mantenerme estrictamente cautelosa en mi comportamiento,
para no darle a mis parientes y conocidos motivos suficientes para molestarse,
ni un pretexto para hablar mal del camino de la Verdad.

Hasta ese entonces, no había considerado seriamente el modo de vestir,
pero pensé en adoptar una postura, y juzgar qué era lo mejor por hacer;
y sin duda alguna, hasta ahora estaba en lo correcto, al hacer algunas modificaciones.

Pero entonces, descubrí que el adversario que merodeaba era el mismo de siempre:
una serpiente maliciosa, engañadora y embustera,
que si logra introducir su cabeza en la más pequeña grieta de nuestro descuido,
rápidamente meterá todo su cuerpo bajo una apariencia de santidad, para lograr,
si es posible, la completa destrucción del alma.
Él vio que su objetivo de arrastrarme a cualquier mal grave y evidente había sido frustrado;
y como no estaba tan familiarizada con sus estratagemas de apariencia angelical,
se introdujo imperceptiblemente en mis deseos de ser celosa por el honor de Dios,
y me elevó por encima de mi propia altura.
Así caí en juzgar, cortar y recortar todo retazo superfluo de mi vestido;
y no quedando satisfecha con eso, pasé de mi guardarropa, a mi tienda,
de modo que en menos de una semana sacrifiqué muchas cosas de valor;
y tan precipitada estaba en ese ciego celo, que me veía impaciente por más combustible.
Una vez concluido el trabajo en casa, como así pensaba,
me dediqué a fijar mi entrometida mirada en los demás.
Eran pocos los que escapaban de mi juicio,
olvidando ese tierno consejo: "`No juzguéis, y no seréis juzgados; no condenéis,
y no seréis condenados.`"
(Lucas 6:37) Me fijaba en cada detalle del comportamiento y de la vestimenta,
hasta que me convertí en una crítica tan grande,
que parecía estar llena de juicios sobre las cosas más insignificantes,
descuidando los asuntos más relevantes, como la fe, la misericordia y el amor de Dios,
que sin duda debería haber considerado, aunque sin dejar de lado lo demás.

El ojo que todo lo escudriña vio mejor que nadie
hasta qué punto había llevado yo todo esto,
y se complació en mirar con compasión el error de mis intenciones,
y misericordiosamente iluminar mi entendimiento;
dejándome ver claramente que me encontraba lejos de ese amor,
sin el cual el apóstol dice, que todas nuestras obras de nada sirven.
Me había aferrado tan firmemente a eso,
que no había visto al engañador hasta que descubrí que esas pasiones predominaban en mí,
como nunca antes había visto.
Mi temperamento se había vuelto poco compasivo y riguroso;
veía al inocente con malos ojos,
y era incapaz de agradarme a mí misma o de agradarme
de los demás. Pero conforme a la medida de mi error,
así también fue mi grado de humillación; y al fin fui llevada tan bajo,
que pude escuchar el silbo apacible de la Sabiduría decirme:
"`¿Quién ha demandado esto de tus manos?`"

Entonces me sentí avergonzada; la serpiente me había engañado,
y con su astucia me había ocasionado más desasosiego que con todos sus rugidos juntos.
Reconocí mi error, y le rogué perdón y protección al Todopoderoso en el porvenir;
quien en Su gran misericordia, reparó la brecha y restauró las calles donde habitar.
Sin embargo,
¡le había dado cabida a aquel jactancioso para que se burlara de
mi indiscreción! Y a menudo traía a mis pensamientos la pérdida
que había sufrido debido a sus venenosas insinuaciones,
incluso cuando no quedaba más rastro de eso que lo necesario para
protegerme de las mismas maquinaciones malignas en el futuro.

Apenas se había disipado ese ejercicio, cuando se me presentó otra prueba.
Como mis parientes seguían ofendidos conmigo porque todavía permanecía en el pueblo,
pensaron en otra artimaña que me sorprendió mucho,
y se sumó a los problemas que me había causado la destrucción de mi mercadería,
como mencioné anteriormente.

Como mi tío había estado en Londres para informarse de nuestros asuntos,
dijo a su regreso, que debido a una gran deuda que había dejado mi padre,
quien llevaba fallecido más de trece años,
se había iniciado una demanda en la cancillería contra
él. Esa información corrió de boca en boca;
y mi tío dijo que como yo era menor de edad,
volvería a tomar los bienes que él me había dejado,
aunque yo no había recibido ni la cuarta parte de mi equivalente.

La inoportuna noticia llegó a mis oídos por boca de muchos.
Digo inoportuna, porque yo había asumido unas deudas del negocio, que según mi tío,
él podía pagar pero se rehusaba a hacerlo.
Mi tía había cerrado mi escuela, y mis antiguos conocidos me habían dejado de comprar,
por lo que mi negocio se había estancado, y había estado así por más de un año,
excepto por la venta de algunas baratijas, como mencioné anteriormente;
de modo que llegué a entender que las cosas que había destruido en mi tienda,
no eran mías. Como tenía cierta familiaridad con el abogado Hollingshead,
le expuse mis aprietos,
y él me dijo con amabilidad que yo podía estar tranquila en cuanto a la deuda;
añadiendo que si hubiera algo de verdad en esa noticia, mi tío ya se lo habría dicho,
pues él acostumbraba pedirle consejo; y que además,
sabía que los acreedores de mi padre habían sido pagados justamente como era debido.
Con respecto a que mi tío confiscara los bienes que me había confiado,
quedaba a criterio de mi tío,
y que él podía negarse a pagar las deudas que yo había asumido
si los recibos habían sido hechos a mi nombre,
a menos que él hubiera dado su palabra de pagarlas.
El abogado me pidió que si tenía algún otro problema, se lo hiciera saber,
y que él hablaría con mi tío en mi nombre.

De esa forma quedé totalmente satisfecha en cuanto a la deuda de mi padre;
y un poco después de eso,
recibí los consoladores respiros del amor de Dios
a través de estas breves y profundas palabras:
"`Confiad, yo he vencido al mundo.`"
Si mi tribulación se hubiera duplicado como la de Job,
ciertamente la habría olvidado en esa época de gracia.
Sin embargo, cuando pasó, encontré que me quedaban dos motivos para lamentarme.
El primero era, la necesidad de pagarle a mis acreedores;
lo que pude lograr en un corto tiempo,
ya que tenía suficiente efectivo para pagarle a todos menos a uno,
de quien había recibido un paquete que estaba casi lleno,
debido a lo poco que había vendido en el negocio;
entonces lo devolví junto con un dinero para cubrir el faltante o algún daño que tuviera.
Lo recibieron con generosidad, y me sentí muy tranquila al respecto.
Pero el otro asunto me fue imposible arreglarlo,
puesto que había destruido toda la mercadería,
y eso me afectó por un tiempo más prolongado.
Sin embargo, como había alcanzado la mayoría de edad, yo misma me encargué de la deuda,
y pude llegar a aceptarlo;
aunque estaba convencida de que si hubiera tenido el consejo de un amigo,
la situación habría sido distinta.

Entonces me lamenté ante el Todopoderoso de que había perdido a mis padres,
ofendido a mis parientes, y no tenía ningún Amigo con experiencia que me aconsejara;
y en efecto, ¿cómo podía esperar que alguien se fijara aunque fuera un poco en mí,
sin que yo lo hiciera saber?

Cada vez me daba más cuenta del peligro en el que podía
caer a causa de mi edad y de otras circunstancias;
y con fervor le pedí al Altísimo que me concediera, en Su sabiduría, un fiel amigo,
que señalara mis errores y que me animara en la virtud;
uno que fuera capaz de instruirme con su experiencia.
Esos deseos a menudo iban acompañados de mis esperanzas y promesas de
que me sometería al consejo y soportaría la reprensión de alguien así;
pero no sabía dónde encontrar a ese amigo.
Tenía miedo de confiar en mi propio juicio,
y a menudo suplicaba al Ser Invisible que me dirigiera en la decisión.

Y así sucedió. J. Toft enfermó y se debilitó tanto,
que varios Amigos se reunieron con él, sin saber si sería su último adiós. Por mi parte,
tuve la oportunidad de estar presente en su habitación,
y oír muchas cosas dignas de consideración; pero lo que más profundamente me impactó,
fue cuando él expresó el ferviente deseo de que yo fuera preservada en la Verdad,
y debido a que era muy joven,
me encomendó a los Amigos presentes para que me tuvieran en cuenta.
Me sentí muy conmovida con tal cuidado paternal, y secretamente supliqué por su vida,
y que su salud fuera restablecida; la cual,
debido a que le agradó al Todopoderoso concederla,
ya no me faltaba un amigo que me cuidara,
creyendo haber encontrado en él lo que anhelaba,
pues su bondad hacia mí se había hecho evidente en aquella circunstancia.
Desde ese entonces le tuve una profunda consideración,
y me propuse buscarlo siempre que necesitara de un consejo.
No pasó mucho tiempo antes de que mis circunstancias parecieron requerirlo.

El Amado de mi alma,
que en mi tierno estado había llenado mi corazón con tanta misericordia,
después escondió Su rostro de mí;
y ya no disfrutaba de los momentos de alivio que antes había gozado tan plenamente.
Esperé y esperé el regreso del que amaba mi alma, preguntando a menudo:
"`¿Por qué se tarda tanto mi Amado?`"
O,
"`¿Qué he hecho desde Su última visita para hacer que se
esconda así de mí?`" Impacientemente lo busqué en mi alcoba,
en las reuniones y en los campos; en los lugares donde acostumbraba recibir Su favor,
pero esos lugares parecían haber perdido su brillo,
y sentía como si mi Amado hubiera perdido Su benevolencia hacia mí. Lo busqué,
y no lo hallé; y estaba lista para preguntar como la esposa en los Cantares:
"`¿Han visto al que ama mi alma?`"
Pasé desconsolada días y noches,
y puedo decir que me lamenté como quien necesita a su compañero.
Aun así, consideré que mis lágrimas no lo conmovían,
y que Su oído parecía estar sordo a todos mis lamentos;
mientras que los arrogantes guardas me herían,
y el cruel enemigo me reprochaba por todo lo que había pasado por causa de mi Amado,
diciéndome que mejor hubiera sido haberme quedado en Egipto,
que consumirme en el desierto.
Fueron grandes los conflictos que enfrenté, sin saber por qué había de ser así;
y temiendo morir a todo lo que era espiritual, determiné recurrir a mi amigo.

Fui a su casa, y mientras esperaba el momento adecuado para dirigirme a él,
las lágrimas corrían por mis mejillas; sin embargo,
cuando fui capaz de desahogar mi pena, experimenté una gran satisfacción; pues,
por su amable interés acerca de mi conducta pasada,
pude confirmar mi opinión respecto a su amistad.
Gracias a su tierno consejo, mi alma se sintió animada a esperar un poco más,
y para mi inexpresable alegría,
unos cuántos días después pude sentir la influencia del Divino
Amor invitando a mi mente a seguir conociendo al Señor. ¡José,
el José espiritual, aún vive! ¡Oh,
por fin había encontrado de nuevo la joya de incalculable valor,
la perla que amaba más que todo lo demás, y la vida de mi esperanza;
sintiendo un revivir semejante al que había experimentado Jacob,
cuando le fue confirmado el bienestar de su hijo!
Mi alma se inclinó bajo el humilde sentido de gratitud, diciendo: "`Basta,
José mi hijo vive todavía; iré, y le veré antes que yo muera.`"

Fue un tiempo de profunda humildad, ternura y amor.
Mi pacto fue renovado; y durante una época permanecí como en una estación de verano,
o "`como el tiempo cuando se oye la voz de la tórtola.`"
Pero de vez en cuando me era imposible dejar de reflexionar en los días pasados,
y pensaba que el menor grado de reconciliación que pudiera lograr con mis tíos,
añadiría a mi felicidad.
A medida que estos pensamientos crecían,
también se incrementaba el deseo de hacer una prueba; y una noche me dirigí a su casa,
y toqué la puerta como una extraña (como en efecto lo era),
ya que no había estado allí por más de dos años.

Su criada me dejó entrar; y supongo que los sorprendí bastante.
Estaban sentados solos junto al fuego.
Yo solamente les dije: "`¿Cómo están?`", y me mantuve dentro de la casa,
un poco lejos de la puerta.
Mi tío se veía muy triste, y no dijo más que: "`No me agrada verte.`"
Mi tía dijo bastante, y dijo muchas groserías por mi llegada.
Me quedé como media hora y después, tras despedirme de ellos,
mi tía me acompañó durante gran parte del camino de regreso a casa,
reprendiéndome mientras avanzábamos, y aunque lo encontré desalentador,
aun así estaba realmente contenta de haberlos podido ver.

Al cabo de unas seis semanas sentí deseos de volver.
Fui, toqué la puerta y permanecí de pie como antes; y unos instantes después mi tío dijo:
"`Puedes sentarte.`"
Entonces mi tía sacó unos libros^
footnote:[Publicaciones contra los Cuáqueros]
(que creo que eran los mismos que Bennet me hubiera prestado),
y leyó varios pasajes absurdos; a lo que yo solamente dije:
"`Espero que no pienses que alguna secta sea tan
ridícula como para pensar y practicar esas cosas.`"
Durante ese tiempo mi tío se sentó a cierta distancia;
yo me quedé allí un poco más que la última vez,
y mi tía me permitió llegar a casa tranquilamente.

Así fui varias veces a visitarlos, a la espera de Su aprobación;
creyendo que ir sin tenerla, me expondría al peligro.
Pero en mi cuarta o quinta visita,
mi tío le dijo a la criada que me preparara algo de comer.
En verdad, habría podido decir que su amor era suficiente;
pues me encontraba tan satisfecha con esa pequeña muestra de cariño,
y con la creciente calma de mi tía, que mi corazón estaba a punto de desbordarse.
Me dirigí a la mesa y antes de comer,
una humilde oración de alabanza a Dios se elevó en mi alma.

A partir de entonces, me tomé la libertad de verlos con frecuencia,
y tuve muchas oportunidades para notar que yo aún ocupaba un lugar en sus corazones,
lo que respondía a mi deseo; pero no podía aspirar a algo más,
ya que siempre ha existido y aún existe,
una enemistad entre la inclinación espiritual y la natural.
Ellos continuaron devolviendo mis visitas,
y comportándose amablemente conmigo desde entonces.

Poco después de cumplir los 24 años me casé con Samuel Lucas,
con el consentimiento de mis Amigos; él era un hombre digno y muy respetado.
Mi tío no asistió a la reunión, pero participó de la cena;
y mi tía nos visitó al día siguiente.
Ambos mostraron amor y afecto hacia mi amable esposo;
y después fueron muy cariñosos con nuestros hijos, especialmente mi tía; y ciertamente,
es satisfactorio recordar los testimonios públicos que dio antes de su muerte,
con respecto a mi comportamiento hacia ella durante el tiempo de mi convencimiento.
Aunque creo que ella continuaba pensando que había hecho bien en
impedir que yo fuera por un camino tan diferente al suyo,
y de aquello que ella consideraba como correcto; aun así,
reconoció que se había enojado y que había sobrepasado los límites de la razón conmigo;
y que nunca me vio comportarme inapropiadamente, ni me oyó decir ninguna palabra grosera.
Ella volvió a mostrarse amable con los Amigos,
como solía hacerlo antes de que yo asistiera a las reuniones;
y en varias ocasiones invitó a algunos Amigos conocidos míos a su casa,
y los atendió con generosidad.

Debo concluir mi narración declarando con honestidad,
¡cuán bendecida fui en mi situación! Pues conté con un esposo amoroso, amable y tierno;
nuestros honestos trabajos fueron prosperados; el cariño de mis parientes fue restaurado;
y por encima de todo, la bendición del Todopoderoso purificaba esos deleites de mi alma,
para la alabanza y la adoración de Su amor.
Me fue permitido morar bajo el tabernáculo de la bondad de Dios,
aunque siempre luchando contra algo dentro de mí, en mis ejercicios secretos.

Así me mantuve tranquilamente dos años, después de mi matrimonio,
hasta que el mejor de los Médicos,
cuyo ojo penetrante había visto la enfermedad de mi alma,
preparó una copa amarga para purgar un veneno que se escondía allí,
y que yo misma había bebido del malicioso adversario de la Verdad, antes,
e incluso después de haber asistido a las reuniones,
y que permanecía allí desde entonces.
A partir de ese momento inició una prueba de fuego,
en la cual mis declaraciones de fe y de amor fueron probadas.

Esto puede considerarse como una segunda parte de mi historia, y la más difícil,
ya que afectó tanto mi vida espiritual como la temporal.
La guerra no fue contra carne ni sangre, sino contra la Majestad en las alturas,
bajo el príncipe de la potestad del aire que opera en los hijos de desobediencia.

Anteriormente mencioné mi deseo de convertirme en una verdadera israelita;
pero sabía muy poco de lo que tenía que atravesar
antes de que mi corazón fuera limpiado de todo engaño,
y liberado de esa ira que el enemigo había estado
acumulando en mi contra para el día de la ira.

Antes de iniciar este difícil relato, debo regresar a mi infancia, y decir,
que la primera vez que oí a una mujer predicar (debido
a un prejuicio aprendido de mis amistades,
y probablemente por una aversión de mi propia naturaleza),
lo consideré algo muy despreciable; y cuánto más lo presenciaba,
más lo aborrecía en lo secreto.
Cuando me uní a los Amigos, esa era una de mis mayores objeciones contra ellos;
pero me esforcé por silenciarla, concluyendo que otros podían hacer lo que quisieran,
y yo haría lo mismo.

Como he mencionado en varias ocasiones, mi tía solía referirse al asunto con frecuencia,
porque ella sabía cuánto me desagradaba esa práctica,
ya que yo se lo había hecho saber antes.
No me cabe duda de que la serpiente, valiéndose de ese prejuicio,
inyectó su veneno todavía más profundo en mí; pues desde que entendí su forma de operar,
he recordado un temor secreto que tenía a veces por ese asunto,
y que el astuto enemigo se había encargado de disipar,
recordándome todas las declaraciones que había hecho en contra de eso.
Sin embargo, persistía la idea de que debía convertirme en una predicadora,
lo que me angustiaba bastante;
pues el único desacuerdo que sentía en cuanto a la disciplina y el orden de la iglesia,
era que les permitieran a las mujeres predicar.
No obstante, me consolaba haciendo muchas resoluciones insensatas en contra de ello.

Se me presentó una buena oportunidad para deshacerme
de los grilletes que el enemigo usaba para atarme;
pero la perdí, y la he recordado muchas veces con dolor.
Estando en una conversación con un Amigo,
me preguntó con franqueza si yo tenía escrúpulos con respecto a algo,
o si estaba satisfecha con los principios de los Amigos.
Decidí no decirle nada,
entendiendo que si mencionaba lo de la predicación de las mujeres,
él pensaría que yo le estaba hablando de mí misma.
Así de confundida me encontraba;
y le respondí que estaba satisfecha con el principio mismo de los Amigos.
En aquel tiempo yo pensaba que la predicación era un acto de amor y de amistad,
independiente de la obediencia; y me habría alegrado como Moisés,
si todo el pueblo del Señor hubiera estado tan dispuesto a hacerlo;
con excepción de las mujeres.

Así continué por algunos años,
hasta que me convertí en una esclava de mis propios temores, al punto de no poder decir:
"`Oh Señor, que se haga Tu voluntad;`" pero como Naamán,
el general del ejército de Siria, ansiaba ser eximida de ese asunto.
Entonces comencé a creer que tales predicaciones eran algo más que ofrendas voluntarias,
y estaba convencida por las numerosas pruebas convincentes,
que las personas de mi propio sexo como las del otro,
habían hablado a mi estado con claridad.
Pero mi perversidad era tal,
que un día me fue muy difícil permanecer en la reunión (mientras una Amiga ministraba),
aunque no podía dejar de reconocer dentro de mí misma,
que habría sido un buen testimonio si hubiera provenido de un hombre.
Así de grande era mi prejuicio; pero aún más grandes, sí, puedo decir,
infinitamente más grandes eran las misericordias de Dios;
pues seguía siendo favorecida con un sentido vivo de Su presencia en mis tiempos
de espera en el Señor. Los misterios de la verdadera divinidad me eran abiertos;
y a través de las influencias del Divino amor,
mi copa se desbordaba con estas afirmaciones: "`¡Oh, mi Amado!
Si me tratas con tanta generosidad, mi pecho será demasiado pequeño para contener tu amor.
¡Oh, aparta tu mano, o ciertamente hablaré de Tu bondad a otros!`"
Y honestamente creo, que si hubiera abrazado esa oportunidad,
y me hubiera unido con el Señor en Su obra,
habría sido liberada de mis temores y escapado de esas circunstancias
adversas que he atravesado con dificultad desde entonces;
pero mi pobre alma retrocedió allí ante la cruz de Cristo,
Cuyo yugo es fácil y Su carga ligera para el de una mente rendida.
Tal era mi debilidad, que por descuido y por las falsas sugerencias del enemigo,
me aparté; y ciertamente puedo decir que cuanto más tiempo llevaba mi carga,
más pesada se volvía; y con dolor tengo que mirar hacia atrás y confesar,
que en vez de abrazar las visitaciones de amor, me uní a mi empedernido enemigo,
y determiné no esperar ni desear ninguna otra revelación. De ese modo endurecí mi corazón,
¡miserable criatura que era!
Y cuando sentía el poder del Todopoderoso operando con Su amor en mi mente,
incluso me atreví a decir:
"`No recibiré más entendimiento;`" y muchas veces cerraba mis ojos, cuando el libro,
por así decirlo,
era puesto en mis manos y el mejor Intérprete estaba cerca
de mí. Así resistí a ese tierno amor que me seguía;
y me levantaba de mi silla y ponía mis pensamientos en otros objectos.

Mi alma está profundamente conmovida por la bondad
de Dios y por Sus continuas misericordias hacia mí,
y bajo la consciencia del triste estado en el que me encontraba entonces;
cuando el enemigo tenía dominio sobre mí,
y Aquel que derramó Su más preciosa sangre por mí
era rechazado a riesgo de la salvación de mi alma;
por lo que me sentía muy lejos de ser una verdadera israelita.

Así continué, ahogando mi propia convicción,
hasta que me adormecí en un letargo espiritual;
en el que me mantuve hasta que el compasivo Dios, quien no quiere la muerte del impío,
se complació en despertarme con una consciencia de lo que yo había estado haciendo.
Entonces encontré suficiente para hacer,
para no hundirme bajo las amargas consideraciones de lo
que yo había traído sobre mí misma a causa de mi rebelión;
pero gracias a la indecible bondad de Dios, fui revivida por Su gracia.

Tras haberme recuperado un poco de ese estado de profunda aflicción,
fui visitada con debilidad de cuerpo;
de modo que tanto yo como otros pensamos que me encontraba muy cerca de la muerte.
Pero le plació al Señor, en una hora inesperada, darme esta certeza: "`No morirás,
sino que vivirás para declarar lo que he hecho por ti.`"
Esto todavía era tan en contra de mis deseos,
que no podía regocijarme de la prolongación de mis días;
porque pensé que entonces sería puesta a prueba.
¡Oh, los días y las noches de conflicto que vinieron después de esa declaración!

Mi semblante cambió, mi salud parecía deteriorarse diariamente;
los lugares solitarios eran testigos de mi dolor; y a medida que pasaban los años,
así aumentaba mi ejercicio, hasta que otra enfermedad me visitó, y estaba,
según todas las apariencias,
más allá de la recuperación. De muy buena gana me hubiera rendido a la muerte,
prefiriendo morir que vivir para no desobedecer más;
pero al Señor le plació probarme una y otra vez en lo secreto de mi alma,
para ver si viviría para obedecer a Sus requerimientos, o si moriría.: mi elección fue,
antes morir que vivir para ser predicadora.
Sin embargo, le plació a Él en Su sabiduría, levantarme de nuevo,
contrario a las expectativas de los que estaban a mi alrededor;
ninguno de los cuales sabía en ese momento, nada de los ejercicios en mi mente,
que se incrementaron a tal grado, que me era imposible expresarlo.
Mi cuerpo temblaba como si lo sacudieran;
y mis gemidos eran como los de una persona agonizando.
Pero había aprendido por experiencia propia a aferrarme al Señor,
y cuando sentía el poder de Su fuerza, buscaba lugares más adecuados para recibirlo,
postrándome en reverencia.
Debido al peso que sentía, exclamaba estas palabras con gran devoción: "`Señor,
¿qué quieres que yo haga?`"
Y como creía que me estaba preparando para un ejercicio mayor,
rogaba con frecuencia que me hiciera apta para sobrellevar lo que, en Su sabiduría,
Él considerara adecuado poner sobre mí. Ciertamente, Su amor era dulce,
y misericordioso Su trato, renovando muchas veces Su pacto con mi alma.
Sin embargo, no se me permitió quedarme aquí,
sino que fui llevada a probar mi fidelidad una vez más.

Mientras estaba en la reunión bajo un consolador estado de espíritu,
sentí una inclinación en mi alma de alabar a Dios con una oración verbal;
y aunque yo había sentido ese mismo poder en mi propio aposento,
y me había sometido allí con gozo,
al no estar dispuesta a rendirme ante esa influencia durante la reunión,
mi corazón y todo dentro de mí quedó perplejo.
Toda la estructura de mi templo fue sacudida,
y eso lo pudo notar una Amiga que estaba sentada detrás de mí,
quien tan pronto terminó la reunión me preguntó cómo estaba;
diciendo que estaba segura de que yo estaba mal.
Le respondí (como era de esperar), que yo me sentía normal.
Esto lo consideré como una buena advertencia,
ya que deseaba mantener mi ejercicio para mí misma.

Pero no transcurrieron muchas reuniones antes de ser probada de nuevo.
Entonces intentaba dejar mi cuerpo lo más firme que podía,
pero me resultaba imposible aquietar mi mente, sabiendo muy bien lo que me sucedía;
aunque el susurrador quería persuadirme de que todo era mi imaginación.

De esa manera perdí tanto tiempo,
que el desagrado del Todopoderoso pareció encenderse contra mí,
y la vida y la muerte fueron presentadas delante de mí. Me encontraba desconcertada,
tanto en casa como fuera, deseando poder ser cualquier otra criatura.
Me atormenté a mí misma hasta que no pude soportarlo más;
y finalmente concluí que sería mejor si se lo hacía saber a un Amigo.
Lo hice, y él me dijo que creía que algo por el estilo me estaba ocurriendo.
Y aunque comprobé que no dependía del hombre (por
la habilidad de su argumento y tierno consejo),
que yo rindiera mi obstinada voluntad, aun así recibí cierto beneficio de él,
y pude reconocer la verdad de sus declaraciones; sin embargo,
no las seguí al pie de la letra,
sino que me convertí en un ejemplo de contradicción. En ocasiones seguía al Señor,
y luego me disponía a hacer lo contrario.
Asistía a las reuniones como un esclavo va a su labor.
En casa no me atrevía a sentarme sola, pues sabía que me enfrentaría con el juicio;
y no podía estar en compañía sin causarme daño por fingir ser alguien que no era.
No quería que sospecharan que todo iba bien,
y llegué a la conclusión de que todo el que me contemplara seriamente,
sabría mi verdadera condición.

Y así me encontraba de agobiada, como entre la piedra de arriba y de abajo del molino;
deseando a menudo la muerte, o nunca haber nacido.
Mi angustia era grande; no podía volver atrás de nuevo,
pues la Semilla de la verdad no me dejaba en paz; no obstante,
albergaba pensamientos de lanzarme a las fauces de la muerte.
Sin embargo, que el nombre del Señor sea alabado por siempre,
pues Su misericordia detuvo al devorador y me preservó;
permitiéndome ver sus falsas insinuaciones y creer que mi vida
(que está en poder del Señor tomar cuando Él quiera) no sería una
expiación suficiente por las rebeliones de las que yo era culpable;
y fui llevada a aborrecer los pensamientos que había concebido.
Fue entonces tan evidente la bondad del Señor, que decidí no faltar a las reuniones.
Pero ¡ay! estando allí, en lugar de mantenerme cerca de los tratos del Señor,
me mantenía lejos de ellos por temor, y me sentaba, según consideraba, seca,
vacía y perdida.
Seca de esos deseos que antes solía poseer; vacía de todo lo bueno; y perdida,
como si el Todopoderoso me hubiera hecho a un lado;
y todo por un temor servil de que no podía acercarme a Dios.
Me sentaba como si no tuviera nada más que hacer,
que ver con anhelo a los demás participando de esa comida que mi alma necesitaba.
Sin embargo, mi estado difería de los que "`vivían reposadamente en Sion,`"^
footnote:[Amós 6:1 LBLA]
porque cuando veía a los que consideraba que estaban en un estado adecuado de mente,
me parecía que se alimentaban de la mesa del Señor,
mientras que mi alma hambrienta yacía en un estado separado de Él,
incapaz de buscar entre las migajas esparcidas.

Así pasé varios días, hasta que en una reunión, casi desvaneciéndome,
me invadió un estado de somnolencia que no era común en mí; sin embargo,
prevaleció hasta el punto en que me vi obligada a pellizcarme para mantenerme despierta.
Entonces consideré que me encontraba peor que nunca en mi vida;
pues cuando era niña tenía la forma, la que dejé para poseer el poder.
Aquí, no encontré un camino tan fácil como yo esperaba; y aunque busqué y busqué,
en lugar de hallar a mi Verdadero Amigo,
encontré a mi enemigo vestido de la doctrina de elección
y reprobación. Un tiempo atrás había sido conducida a eso,
pero en ese momento me resultaba más difícil,
debido a que no me sentía digna de librarme de ello.
Luché fuertemente contra la tentación de destruirme a mí misma,
y deseaba tontamente que algún accidente se encargara de ello.
Pero las riquezas de la gracia de Dios aparecieron nuevamente;
fui llevada a ver y a reconocer, que si mi alma perecía eternamente,
el Señor sería justo en su forma de proceder conmigo;
y esas consideraciones tuvieron un efecto sobre mí.

Yo deseaba ser llevada de vuelta a mi condición anterior,
para poder tener acceso a Su poder, ser testigo de Su amor, y ser una vez más probada.
Mi pluma no sería suficiente para describir toda la misericordia
y clemencia de la bondad de mi Creador para conmigo.
Entonces pude ver que mi perdón estaba sellado; pero mi paz no duró mucho tiempo,
pues el Señor me puso a prueba una y otra vez; sin embargo,
no me rendí. Estaba consciente de que retrocedía de ese
Poder que estaba listo como una mano para rendirme ayuda,
y por eso empeoraba más y más. "`Nunca te irá bien,`" me sugería el enemigo.
Yo no sabía qué camino debía tomar; estaba cansada de mi propia terquedad,
y decidí probar lo que se podía ganar con un duro trato del cuerpo.
Como no podía trabajar, comía muy poco.
Buscaba varias maneras de afligirme, y pensaba cuán contenta estaría si no tuviera lengua.
Nuevamente me di cuenta de que el viejo incitador estaba cerca para aumentar mi aflicción;
que, junto con mi propia desobediencia,
hacía que toda la creación pareciera estar en contra de mí. ¡Oh!
Me encontraba tan desconcertada que decía: "`Ahora caeré por la mano de mi enemigo.`"
Me afligía y me irritaba conmigo misma y con todo lo que estaba a mi alrededor,
y no lograba alcanzar verdadera sumisión.

En una ocasión, mientras reflexionaba seriamente sobre mi situación,
estos pensamientos pasaron por mi mente y me sorprendieron: "`Si eres un Dios de poder,
pon en mí el querer.`"
Tan pronto pasó eso, le siguió esta sugerencia: "`Alma, aborrece esta suposición;
porque aunque es un Dios de poder, Él redimirá en Su propio tiempo.`"
Estaba perpleja, y le dije: "`Señor, ¿qué es esto?`"
y se me presentó lo siguiente: "`Hay una gran batalla en el cielo,
Miguel y el dragón.`" Después de que pasó el revoloteo, recordé el pasaje que dice:
"`En el día de mi poder, mi pueblo se ofrecerá voluntariamente;`"^
footnote:[Salmo 110:3]
y fui consolada de esa manera.

Por esa época ocurrió otro hecho muy particular, que no puedo dejar de mencionar.
Estaba completamente persuadida de que si continuaba en esa terquedad,
mi casa sería destruida; y al cabo de un mes,
fuimos librados del fuego de una manera asombrosa ante los ojos de muchos testigos;
durante el cual,
mientras que unos estaban ocupados preguntándose sobre cómo había ocurrido,
yo me encontraba ocupada reflexionando,
en que yo había sido la verdadera causa;
lo que me inundó de humildes agradecimientos a Dios por habernos preservado misericordiosamente.
El mundo, comparativamente hablando, parecía estar cerca de su fin en cuanto a mí,
y era como si se estuviera aproximando un eclipse total.
Cada escena y cada cosa parecían sombrías, y dondequiera que dirigía mi mirada,
aparecía un Dios furioso.
No había refugio para mí, nada con que defenderme, ninguna manera de escapar,
y sentí que era inevitable que mi vida natural cediera.

Poco después volvió la prueba de mi obediencia; y en ese momento,
el enemigo de mi alma me sugirió que si yo me levantaba para hablar en la reunión,
no iba a poder mantenerme de pie; pero gracias al Todopoderoso,
fui fortalecida en el intento y descubrí que el enemigo era un mentiroso.
El haber expresado estas pocas palabras en obediencia al Señor produjo un cambio bendito.
Entonces era como si existieran un cielo nuevo y una tierra nueva;
las cosas viejas habían pasado,
y todas las cosas pertenecientes a mi estado habían sido hechas nuevas.
Ya no quedaba más sentido de culpa por la desobediencia del pasado,
sino que nuevos acuerdos y pactos llenaron aquel día de gozo.
No obstante, todavía esperaba con ansiedad el siguiente día de reunión;
y aunque en una época sentí que las reuniones no llegaban lo suficientemente rápido,
en ese momento parecían llegar demasiado pronto.
En dos o tres reuniones, me senté bajo un grado de temor sumiso;
deseando todavía verdaderamente conservar mi integridad y obediencia.
Finalmente llegó una segunda prueba; fui impulsada a arrodillarme,
y mientras ojeaba a mi alrededor,
mi alma suspiró secretamente de esta forma delante del Señor:
"`Este es el lugar de mi ejecución;`" y viendo el reclinatorio dije:
"`Este es el bloque donde debo rendir mi orgullo natural como testimonio de mi obediencia.
¡Acuérdate de mí, oh Señor!
Y también de los conflictos que atravieso para servirte.
¡Acepta, oh Señor el sacrificio!`"
Luego me arrodillé; y cuando me levanté, esto vino a mi mente:
"`La vida que debo vivir ahora, debe ser por la fe en Cristo Jesús.`"

Mientras perseveraba en obediencia sentía una satisfacción indecible,
que gradualmente sacaba a mi alma del lugar de esclavitud y servidumbre.
Así, gracias a la bondad de Dios,
las plazas fortificadas del pecado y de Satanás fueron derribadas,
y el gozo de mi salvación fue restablecido.
Los tiempos y los días de reunión se volvieron placenteros,
mientras mi alma adoraba al Dios viviente, como en la casa de oración.

Mientras esté en la orilla de la liberación,
pronunciando hosanna en las alturas con el arpa de acción de gracias puesta en mis manos,
mi canto será de las misericordias y de los juicios
por los que mi alma ha sido hasta ahora redimida;
y de la victoria del Cordero, por Cuya diestra y brazos eternos,
los enemigos de mi alma han retrocedido, han sido dispersados y puestos en fuga.

Y ahora, ¿qué pagaré a Jehová por esta obra tan gloriosa y por la salvación de mi alma?
--sino el humilde reconocimiento de una de las más indignas y viles de los pecadores;
quien, por Su bondadosa misericordia,
ha sido capacitada y animada a atribuirle a Él el honor, la adoración,
el dominio y el renombre, con alabanzas y acciones de gracias,
como resultado de Su amor eterno, por los siglos de los siglos.

[verse]
____
Tras examinar la trama,
Mi alma se aviva como una llama
De un santo celo, para así conocer
La mano de Dios en mi quehacer.
¡Oh que en esto yo pueda confiar
Y que el Juez justo me pueda probar!
Este es mi deseo mayor
que mi fe, esperanza y amor
no me avergüencen, antes bien estimar
y más allá de la tumba poder heredar
un disfrute, Señor; que me puedas permitir
vivir en temor y en gracia morir;
Y que en alas de aleluya pueda estar
y mi alma a nuestro Rey encontrar.
____
